[divisions]
    # Short names.
    o = {name = "O",min=14,max=999}
    j = {name = "J",min=19,max=22.5}
    d = {name = "D",min=0,max=13}
    sj = {name = "SJ",min=14,max=18.5}
    m1 = {name = "M1",min=39.5,max=49.5}
    m2 = {name = "M2",min=50,max=59.5}
    m3 = {name = "M3",min=60,max=69.5}
    m4 = {name = "M4",min=70,max=999}
    hs = {name = "HS",min=0,max=999}
    c = {name = "C",min=14,max=24}
    g = {name = "G",min=0,max=999}
    n = {name = "N",min=0,max=999}
    m = {name = "M", min=39.5, max=999}

    # Long names.
    open = {name = "Open",min=14,max=999}
    junior = {name = "Junior",min=19,max=22.5}
    subjunior = {name = "Sub-Junior",min=14,max=18.5}
    novice = {name = "Novice",min=14,max=999}
    master = {name = "Master",min=39.5,max=999}
    master1 = {name = "Master 1",min=39.5,max=49.5}
    master2 = {name = "Master 2",min=50,max=59.5}
    master3 = {name = "Master 3",min=60,max=69.5}
    master4 = {name = "Master 4",min=70,max=999}
    developmental = {name = "Developmental",min=0,max=13}
    college = {name = "College", min=14,max=24}


[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-12-31"]
    sex = "M"

[weightclasses.new_F]
    classes = ["47","52","57","63","69","76","84","84+"]
    date_range=["2021-01-01","9999-12-31"]
    sex = "F"

[weightclasses.default_F]
    classes = ["47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","2020-12-31"]
    sex = "F"

[weightclasses.junior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-12-31"]
    sex = "M"
    divisions = ["J","SJ","C"]

[weightclasses.junior_F]
    classes = ["43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-12-31"]
    sex = "F"
    divisions = ["J","SJ","C"]

[weightclasses.developmental_M]
    classes = ["33","38","43","48","53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-12-31"]
    sex = "M"
    divisions = ["D", "Developmental"]

[weightclasses.developmental_F]
    classes = ["31","35","39","43","47","52","57","57+"]
    date_range=["2011-01-01","9999-12-31"]
    sex = "F"
    divisions = ["D", "Developmental"]



[exemptions]
    1601 = ["ExemptWeightClassConsistency", "ExemptDivision"]
    1602 = ["ExemptWeightClassConsistency", "ExemptDivision"]
    1603 = ["ExemptWeightClassConsistency", "ExemptDivision"]
    1604 = ["ExemptWeightClassConsistency", "ExemptDivision"]
    1605 = ["ExemptWeightClassConsistency", "ExemptDivision"]
    1606 = ["ExemptWeightClassConsistency", "ExemptDivision"]
    1607 = ["ExemptWeightClassConsistency", "ExemptDivision"] 
	2301 = ["ExemptWeightClassConsistency", "ExemptDivision"] 
    2303 = ["ExemptWeightClassConsistency", "ExemptDivision"] 	
