[divisions]
    o = {name ="O",min=14,max=999}
    j = {name = "J",min=14,max=22.5}
    d = {name = "D",min=0,max=13}
    sj = {name = "SJ",min=14,max=17.5}
    m1 = {name = "M1",min=39.5,max=49.5}
    m2 = {name = "M2",min=49.5,max=59.5}
    m3 = {name = "M3",min=59.5,max=69.5}
    m4 = {name = "M4",min=69.5,max=999}

[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","2018-08-24"]
    sex = "M"

[weightclasses.default_F]
    classes = ["47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","2018-08-24"]
    sex = "F"

[weightclasses.junior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","2018-08-24"]
    sex = "M"
    divisions = ["J","SJ"]

[weightclasses.junior_F]
    classes = ["43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","2018-08-24"]
    sex = "F"
    divisions = ["J","SJ"]

[weightclasses.developmental_M]
    classes = ["33","38","43","48","53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","2018-08-24"]
    sex = "M"
    divisions = ["D"]



[exemptions]
    1601 = ["ExemptWeightClassConsistency", "ExemptDivision"]
    1602 = ["ExemptWeightClassConsistency", "ExemptDivision"]
    1603 = ["ExemptWeightClassConsistency", "ExemptDivision"]
    1604 = ["ExemptWeightClassConsistency", "ExemptDivision"]
    1605 = ["ExemptWeightClassConsistency", "ExemptDivision"]
    1606 = ["ExemptWeightClassConsistency", "ExemptDivision"]
    1607 = ["ExemptWeightClassConsistency", "ExemptDivision"]  