[divisions]
    #Men's divisions
    mcopen = {name ="M-C-Open",min=0,max=999,equipment="Raw"}
    meopen = {name ="M-E-Open",min=0,max=999,equipment="Single-ply"}
    mcu23 = {name ="M-C-U23",min=14,max=22.5,equipment="Raw"}
    meu23 = {name ="M-E-U23",min=14,max=22.5,equipment="Single-ply"}
    mcu20 = {name ="M-C-U20",min=14,max=19.5,equipment="Raw"}
    meu20 = {name ="M-E-U20",min=14,max=19.5,equipment="Single-ply"}
    mcu18 = {name ="M-C-U18",min=14,max=17.5,equipment="Raw"}
    meu18 = {name ="M-E-U18",min=14,max=17.5,equipment="Single-ply"}
    mcu16 = {name ="M-C-U16",min=14,max=15.5,equipment="Raw"}
    meu16 = {name ="M-E-U16",min=14,max=15.5,equipment="Single-ply"}
    mcm1 = {name ="M-C-M1",min=39.5,max=48.5,equipment="Raw"}
    mem1 = {name ="M-E-M1",min=39.5,max=48.5,equipment="Single-ply"}
    mcm2 = {name ="M-C-M2",min=49.5,max=58.5,equipment="Raw"}
    mem2 = {name ="M-E-M2",min=49.5,max=58.5,equipment="Single-ply"}
    mcm3 = {name ="M-C-M3",min=59.5,max=68.5,equipment="Raw"}
    mem3 = {name ="M-E-M3",min=59.5,max=68.5,equipment="Single-ply"}
    mcm4 = {name ="M-C-M4",min=69.5,max=78.5,equipment="Raw"}
    mem4 = {name ="M-E-M4",min=69.5,max=78.5,equipment="Single-ply"}
    mcm5 = {name ="M-C-M5",min=79.5,max=999,equipment="Raw"}
    mem5 = {name ="M-E-M5",min=79.5,max=999,equipment="Single-ply"}

    #Women's divisions
    fcopen = {name ="F-C-Open",min=0,max=999,equipment="Raw"}
    feopen = {name ="F-E-Open",min=0,max=999,equipment="Single-ply"}
    fcu23 = {name ="F-C-U23",min=14,max=22.5,equipment="Raw"}
    feu23 = {name ="F-E-U23",min=14,max=22.5,equipment="Single-ply"}
    fcu20 = {name ="F-C-U20",min=14,max=19.5,equipment="Raw"}
    feu20 = {name ="F-E-U20",min=14,max=19.5,equipment="Single-ply"}
    fcu18 = {name ="F-C-U18",min=14,max=17.5,equipment="Raw"}
    feu18 = {name ="F-E-U18",min=14,max=17.5,equipment="Single-ply"}
    fcu16 = {name ="F-C-U16",min=14,max=15.5,equipment="Raw"}
    feu16 = {name ="F-E-U16",min=14,max=15.5,equipment="Single-ply"}
    fcm1 = {name ="F-C-M1",min=39.5,max=48.5,equipment="Raw"}
    fem1 = {name ="F-E-M1",min=39.5,max=48.5,equipment="Single-ply"}
    fcm2 = {name ="F-C-M2",min=49.5,max=58.5,equipment="Raw"}
    fem2 = {name ="F-E-M2",min=49.5,max=58.5,equipment="Single-ply"}
    fcm3 = {name ="F-C-M3",min=59.5,max=68.5,equipment="Raw"}
    fem3 = {name ="F-E-M3",min=59.5,max=68.5,equipment="Single-ply"}
    fcm4 = {name ="F-C-M4",min=69.5,max=999,equipment="Raw"}
    fem4 = {name ="F-E-M4",min=69.5,max=999,equipment="Single-ply"}
    fcm5 = {name ="F-C-M5",min=79.5,max=999,equipment="Raw"}
    fem5 = {name ="F-E-M5",min=79.5,max=999,equipment="Single-ply"}

    #Misc divisions
    mcg = {name ="M-C-G",min=0,max=999,equipment="Raw"} #Guest
    meg = {name ="M-E-G",min=0,max=999,equipment="Single-ply"}
    fcg = {name ="F-C-G",min=0,max=999,equipment="Raw"}
    feg = {name ="F-E-G",min=0,max=999,equipment="Single-ply"}
    mcn = {name ="M-C-N",min=0,max=999,equipment="Raw"} #Novice
    men = {name ="M-E-N",min=0,max=999,equipment="Single-ply"}
    fcn = {name ="F-C-N",min=0,max=999,equipment="Raw"}
    fen = {name ="F-E-N",min=0,max=999,equipment="Single-ply"}
[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"

[weightclasses.junior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["M-C-U23","M-E-U23","M-C-U20","M-E-U20","M-C-U18","M-E-U18","M-C-U16","M-E-U16"]

[weightclasses.junior_F]
    classes = ["43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"
    divisions = ["F-C-U23","F-E-U23","F-C-U20","F-E-U20","F-C-U18","F-E-U18","F-C-U16","F-E-U16"]

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"

[exemptions]
 
    0604 = ["ExemptDivision"]
    0605 = ["ExemptDivision"]
    0606 = ["ExemptDivision"]
