[divisions]
    open = {name ="Open",min=0,max=999}

    submasters = {name ="Submasters",min=33,max=39}
    teen1315 = {name ="Teen 1",min=13,max=15}
    teen1617 = {name ="Teen 2",min=16,max=17}
    teen1819 = {name ="Teen 3",min=18,max=19}
    juniors2023 = {name ="Juniors",min=20,max=23}
    masters1 = {name ="Masters 1",min=40,max=44}
    masters2 = {name ="Masters 2",min=45,max=49}
    masters3 = {name ="Masters 3",min=50,max=54}
    masters4 = {name ="Masters 4",min=55,max=59}
    masters5 = {name ="Masters 5",min=60,max=64}
    masters6 = {name ="Masters 6",min=65,max=69}
    masters7 = {name ="Masters 7",min=70,max=74}
    masters8 = {name ="Masters 8",min=75,max=79}
    masters9 = {name ="Masters 9",min=80,max=999}

[weightclasses.default_M]
    classes = ["56","60","67.5","75","82.5","90","100","110","125","125+","140","140+"]
    date_range = ["2016-01-01","9999-99-99"]
    sex = "M"



[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","110","110+"]
    date_range = ["2016-01-01","9999-99-99"]
    sex = "F"

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-00-00","2015-12-31"]
    sex = "F"

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+","140","140+"]
    date_range = ["0000-00-00","2015-12-31"]
    sex = "M"

[exclusions]
