# Configuration for GPC-IRL.

[rulesets.default]
    ruleset = ["CombineRawAndWraps", "CombineSingleAndMulti"]
    date_range = ["0000-01-01", "9999-01-01"]

[divisions]
    mo = {name ="MO", min=0, max=999, sex="M", equipment=["Raw","Wraps"]}
    fo = {name ="FO", min=0, max=999, sex="F", equipment=["Raw","Wraps"]}
    msm = {name ="MSM", min=33, max=39, sex="M", equipment=["Raw","Wraps"]}
    fsm = {name ="FSM", min=33, max=39, sex="F", equipment=["Raw","Wraps"]}
    mt1 = {name ="MT-1", min=13, max=15, sex="M", equipment=["Raw","Wraps"]}
    mt2 = {name ="MT-2", min=16, max=17, sex="M", equipment=["Raw","Wraps"]}
    mt3 = {name ="MT-3", min=18, max=19, sex="M", equipment=["Raw","Wraps"]}
    ft = {name ="F-T", min=13, max=19, sex="F", equipment=["Raw","Wraps"]}
    ft1 = {name ="FT-1", min=13, max=15, sex="F", equipment=["Raw","Wraps"]}
    ft2 = {name ="FT-2", min=16, max=17, sex="F", equipment=["Raw","Wraps"]}
    ft3 = {name ="FT-3", min=18, max=19, sex="F", equipment=["Raw","Wraps"]}
    mj = {name ="MJ", min=20, max=23, sex="M", equipment=["Raw","Wraps"]}
    fj = {name ="FJ", min=20, max=23, sex="F", equipment=["Raw","Wraps"]}
    mm1 = {name ="M-1", min=40, max=44, sex="M", equipment=["Raw","Wraps"]}
    fm1 = {name ="F-1", min=40, max=44, sex="F", equipment=["Raw","Wraps"]}
    mm2 = {name ="M-2", min=45, max=49, sex="M", equipment=["Raw","Wraps"]}
    fm2 = {name ="F-2", min=45, max=49, sex="F", equipment=["Raw","Wraps"]}
    mm3 = {name ="M-3", min=50, max=54, sex="M", equipment=["Raw","Wraps"]}
    fm3 = {name ="F-3", min=50, max=54, sex="F", equipment=["Raw","Wraps"]}
    mm4 = {name ="M-4", min=55, max=59, sex="M", equipment=["Raw","Wraps"]}
    fm4 = {name ="F-4", min=55, max=59, sex="F", equipment=["Raw","Wraps"]}
    mm5 = {name ="M-5", min=60, max=64, sex="M", equipment=["Raw","Wraps"]}
    fm5 = {name ="F-5", min=60, max=64, sex="F", equipment=["Raw","Wraps"]}
    mm6 = {name ="M-6", min=65, max=69, sex="M", equipment=["Raw","Wraps"]}
    fm6 = {name ="F-6", min=65, max=69, sex="F", equipment=["Raw","Wraps"]}
    mm7 = {name ="M-7", min=70, max=74, sex="M", equipment=["Raw","Wraps"]}
    fm7 = {name ="F-7", min=70, max=74, sex="F", equipment=["Raw","Wraps"]}
    mm8 = {name ="M-8", min=75, max=79, sex="M", equipment=["Raw","Wraps"]}
    fm8 = {name ="F-8", min=75, max=79, sex="F", equipment=["Raw","Wraps"]}
    mm9 = {name ="M-9", min=80, max=999, sex="M", equipment=["Raw","Wraps"]}
    fm9 = {name ="F-9", min=80, max=999, sex="F", equipment=["Raw","Wraps"]}
    moe = {name ="MOE", min=0, max=999, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    foe = {name ="FOE", min=0, max=999, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mje = {name ="MJE", min=20, max=23, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    fje = {name ="FJE", min=20, max=23, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mte1 = {name ="MT-E1", min=13, max=15, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mte2 = {name ="MT-E2", min=16, max=17, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mte3 = {name ="MT-E3", min=18, max=19, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mem1 = {name ="M-E1", min=40, max=44, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    fem1 = {name ="F-E1", min=40, max=44, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mem2 = {name ="M-E2", min=45, max=49, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    fem2 = {name ="F-E2", min=45, max=49, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mem3 = {name ="M-E3", min=50, max=54, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    fem3 = {name ="F-E3", min=50, max=54, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mem4 = {name ="M-E4", min=55, max=59, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    fem4 = {name ="F-E4", min=55, max=59, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mem5 = {name ="M-E5", min=60, max=64, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    fem5 = {name ="F-E5", min=60, max=64, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mem6 = {name ="M-E6", min=65, max=69, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mem7 = {name ="M-E7", min=70, max=74, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}

[weightclasses.default_M]
    classes = ["56","60","67.5","75","82.5","90","100","110","125","140","125+","140+"]
    date_range = ["2016-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","110","110+"]
    date_range = ["2016-01-01","9999-01-01"]
    sex = "F"

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2015-12-31"]
    sex = "F"

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","125+","140+"]
    date_range = ["0000-01-01","2015-12-31"]
    sex = "M"

[exemptions]
