[divisions]
    open = {name ="Open",min=0,max=999}


#These weightclasses are just here as placeholders
[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","125+","140+"]
    date_range = ["1998-01-01","9999-01-01"]
    sex = "M"

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["0000-01-01","1997-12-31"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]
    1201 = ["check_row_weightclass_consistency"]
