[divisions]
    #USAPL Divisions
    RO = {name ="R-O",min=0,max=999}
    RHS = {name ="R-HS",min=13,max=19}
    RC = {name ="R-C",min=0,max=999}
    RJR = {name = "R-JR",min=0,max=23}
    RY = {name = "R-Y",min=8,max=13}
    RY1 = {name = "R-Y1",min=8,max=9}
    RY2 = {name = "R-Y2",min=10,max=11}
    RY3 = {name = "R-Y3",min=12,max=13}
    RT = {name = "R-T",min=0,max=19}
    RT1 = {name = "R-T1",min=14,max=15}
    RT2 = {name = "R-T2",min=16,max=17}
    RT3 = {name = "R-T3",min=18,max=19}
    RM1A = {name = "R-M1a",min=39.5,max=43.5}
    RM1B = {name = "R-M1b",min=44.5,max=48.5}
    RM2A = {name = "R-M2a",min=49.5,max=53.5}
    RM2B = {name = "R-M2b",min=54.5,max=58.5}
    RM3A = {name = "R-M3a",min=59.5,max=63.5}
    RM3B = {name = "R-M3b",min=64.5,max=68.5}
    RM4A = {name = "R-M4a",min=69.5,max=73.5}
    RM4B = {name = "R-M4b",min=74.5,max=78.5}
    O = {name ="O",min=0,max=999}
    C = {name ="C",min=0,max=999}
    HS = {name ="R-HS",min=13,max=19}
    JR = {name = "JR",min=0,max=23}
    Y = {name = "Y",min=8,max=13}
    Y1 = {name = "Y1",min=8,max=9}
    Y2 = {name = "Y2",min=10,max=11}
    Y3 = {name = "Y3",min=12,max=13}
    T = {name = "T",min=0,max=19}
    T1 = {name = "T1",min=14,max=15}
    T2 = {name = "T2",min=16,max=17}
    T3 = {name = "T3",min=18,max=19}
    M1A = {name = "M1a",min=39.5,max=43.5}
    M1B = {name = "M1b",min=44.5,max=48.5}
    M2A = {name = "M2a",min=49.5,max=53.5}
    M2B = {name = "M2b",min=54.5,max=58.5}
    M3A = {name = "M3a",min=59.5,max=63.5}
    M3B = {name = "M3b",min=64.5,max=68.5}
    M4A = {name = "M4a",min=69.5,max=73.5}
    M4B = {name = "M4b",min=74.5,max=78.5}

    #IPF Divisons
    RM1 = {name = "R-M1",min=39.5,max=48.5}
    RM2 = {name = "R-M2",min=49.5,max=58.5}
    RM3 = {name = "R-M3",min=59.5,max=68.5}
    RM4 = {name = "R-M4",min=69.5,max=999}
    M1 = {name = "M1",min=39.5,max=48.5}
    M2 = {name = "M2",min=49.5,max=58.5}
    M3 = {name = "M3",min=59.5,max=68.5}
    M4 = {name = "M4",min=69.5,max=999}

[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"

[weightclasses.junior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["R-JR","R-T","JR","T"]

[weightclasses.junior_F]
    classes = ["43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"
    divisions = ["R-JR","R-T","JR","T"]

[weightclasses.youth_M]
    classes = ["30","35","40","44","48","53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["R-Y","R-Y1","R-Y2","R-Y3","Y","Y1","Y2","Y3"]

[weightclasses.youth_F]
    classes = ["30","35","40","43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"
    divisions = ["R-Y","R-Y1","R-Y2","R-Y3","Y","Y1","Y2","Y3"]

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"

[exemptions]
   