# Configuration for APLA.

[options]
    require_manual_disambiguation = true

[divisions]
    # From the IPF Technical Rulebook located at https://www.powerlifting.sport/rules/codes/info/technical-rules
    open = {name ="Open",min=0,max=999}
    junior = {name = "Junior",min=0,max=23.5}
    subjunior = {name = "Sub-Junior",min=0,max=18.5}
    masters1 = {name = "Masters 1",min=39.5,max=48.5}
    masters2 = {name = "Masters 2",min=49.5,max=58.5}
    masters3 = {name = "Masters 3",min=59.5,max=68.5}
    masters4 = {name = "Masters 4",min=69.5,max=999}
	specialolympics = {name = "Special Olympics",min=0,max=999}

[weightclasses.IPF_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["2024-01-01","9999-01-01"]
    sex = "M"

[weightclasses.IPF_F]
    classes = ["47","52","57","63","69","76","84","84+"]
    date_range=["2024-01-01","9999-01-01"]
    sex = "F"

[weightclasses.IPF_juniorM]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2024-01-01","9999-01-01"]
    sex = "M"
    divisions = ["Junior","Sub-Junior"]

[weightclasses.IPF_juniorF]
    classes = ["43","47","52","57","63","69","76","84","84+"]
    date_range=["2024-01-01","9999-01-01"]
    sex = "F"
    divisions = ["Junior","Sub-Junior"]

[exemptions]
    2406 = ["ExemptLiftOrder"]
