# Configuration for ESDT.

[divisions]
    open = {name ="Open", min=0, max=999}
    t = {name ="Teen", min=13, max=19}
    juniors = {name ="Juniors", min=20, max=23}
    masters = {name ="Masters", min=40, max=49}

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","9999-12-31"]
    sex = "F"

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["0000-01-01","9999-12-31"]
    sex = "M"

[exemptions]
