# Configuration for the SAPF

[divisions]
	# Old divisions (pre-2019 or so).
    open = {name ="Open",min=0,max=999}
    juniors = {name = "Juniors",min=0,max=22.5}
    subjuniors = {name = "Sub-Juniors",min=0,max=17.5}
    masters1 = {name = "Masters 1",min=39.5,max=48.5}
    masters2 = {name = "Masters 2",min=49.5,max=58.5}
    masters3 = {name = "Masters 3",min=59.5,max=68.5}
    masters4 = {name = "Masters 4",min=69.5,max=999}

	# USAPL-style divisions.
	mro = {name="MR-O", min=0, max=999, sex="M", equipment="Raw"}
	mrsj = {name="MR-SJ", min=0, max=17.5, sex="M", equipment="Raw"}
	mrjr = {name="MR-Jr", min=0, max=22.5, sex="M", equipment="Raw"}
	mrm1 = {name="MR-M1", min=39.5, max=48.5, sex="M", equipment="Raw"}
	mrm2 = {name="MR-M2", min=49.5, max=58.5, sex="M", equipment="Raw"}
	mrm3 = {name="MR-M3", min=59.5, max=68.5, sex="M", equipment="Raw"}
	mrm4 = {name="MR-M4", min=69.5, max=999, sex="M", equipment="Raw"}

	mo = {name="M-O", min=0, max=999, sex="M", equipment="Single-ply"}
	msj = {name="M-SJ", min=0, max=17.5, sex="M", equipment="Single-ply"}
	mjr = {name="M-Jr", min=0, max=22.5, sex="M", equipment="Single-ply"}
	mm1 = {name="M-M1", min=39.5, max=48.5, sex="M", equipment="Single-ply"}
	mm2 = {name="M-M2", min=49.5, max=58.5, sex="M", equipment="Single-ply"}
	mm3 = {name="M-M3", min=59.5, max=68.5, sex="M", equipment="Single-ply"}
	mm4 = {name="M-M4", min=69.5, max=999, sex="M", equipment="Single-ply"}

	fro = {name="FR-O", min=0, max=999, sex="F", equipment="Raw"}
	fry = {name="FR-Y", min=0, max=13, sex="F", equipment="Raw"}
	frsj = {name="FR-SJ", min=0, max=17.5, sex="F", equipment="Raw"}
	frjr = {name="FR-Jr", min=0, max=22.5, sex="F", equipment="Raw"}
	frm1 = {name="FR-M1", min=39.5, max=48.5, sex="F", equipment="Raw"}
	frm2 = {name="FR-M2", min=49.5, max=58.5, sex="F", equipment="Raw"}
	frm3 = {name="FR-M3", min=59.5, max=68.5, sex="F", equipment="Raw"}
	frm4 = {name="FR-M4", min=69.5, max=999, sex="F", equipment="Raw"}

	fo = {name="F-O", min=0, max=999, sex="F", equipment="Single-ply"}
	fsj = {name="F-SJ", min=0, max=17.5, sex="F", equipment="Single-ply"}
	fjr = {name="F-Jr", min=0, max=22.5, sex="F", equipment="Single-ply"}
	fm1 = {name="F-M1", min=39.5, max=48.5, sex="F", equipment="Single-ply"}
	fm2 = {name="F-M2", min=49.5, max=58.5, sex="F", equipment="Single-ply"}
	fm3 = {name="F-M3", min=59.5, max=68.5, sex="F", equipment="Single-ply"}
	fm4 = {name="F-M4", min=69.5, max=999, sex="F", equipment="Single-ply"}

	# Paralympics.
	mrpo = {name="MR-PO", min=0, max=999, sex="M", equipment="Raw"}
	mrpsj = {name="MR-PSJ", min=0, max=17.5, sex="M", equipment="Raw"}
	mrpjr = {name="MR-PJr", min=0, max=22.5, sex="M", equipment="Raw"}
	mrpm1 = {name="MR-PM1", min=39.5, max=48.5, sex="M", equipment="Raw"}
	mrpm2 = {name="MR-PM2", min=49.5, max=58.5, sex="M", equipment="Raw"}
	mrpm3 = {name="MR-PM3", min=59.5, max=68.5, sex="M", equipment="Raw"}
	mrpm4 = {name="MR-PM4", min=69.5, max=999, sex="M", equipment="Raw"}
	frpo = {name="FR-PO", min=0, max=999, sex="F", equipment="Raw"}
	frpsj = {name="FR-PSJ", min=0, max=17.5, sex="F", equipment="Raw"}
	frpjr = {name="FR-PJr", min=0, max=22.5, sex="F", equipment="Raw"}
	frpm1 = {name="FR-PM1", min=39.5, max=48.5, sex="F", equipment="Raw"}
	frpm2 = {name="FR-PM2", min=49.5, max=58.5, sex="F", equipment="Raw"}
	frpm3 = {name="FR-PM3", min=59.5, max=68.5, sex="F", equipment="Raw"}
	frpm4 = {name="FR-PM4", min=69.5, max=999, sex="F", equipment="Raw"}

[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["47","52","57","63","69","76","84","84+"]
    date_range=["2020-01-01","9999-01-01"]
    sex = "F"

[weightclasses.year2020_F]
    classes = ["47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","2019-12-31"]
    sex = "F"

[weightclasses.junior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["Juniors","Sub-Juniors","MR-SJ","MR-Jr","M-SJ","M-Jr","MR-PSJ","MR-PJr"]

[weightclasses.junior_F]
    classes = ["43","47","52","57","63","69","76","84","84+"]
    date_range=["2020-01-01","9999-01-01"]
    sex = "F"
    divisions = ["Juniors","Sub-Juniors","FR-SJ","FR-Jr","F-SJ","F-Jr"]

[weightclasses.year2020_junior_F]
    classes = ["43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","2019-12-31"]
    sex = "F"
    divisions = ["Juniors","Sub-Juniors","FR-SJ","FR-Jr","F-SJ","F-Jr"]

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"

[exemptions]
  
