[divisions]
    am_open = {name = "Amateur Open", min = 0, max = 999,tested="Yes"}
    am_youth = {name = "Amateur Youth", min = 5, max = 12,tested="Yes"}
    am_teen_13_15 = {name = "Amateur Teen 13-15", min = 13, max = 15,tested="Yes"}
    am_teen_16_17 = {name = "Amateur Teen 16-17", min = 16, max = 17,tested="Yes"}
    am_teen_18_19 = {name = "Amateur Teen 18-19", min = 18, max = 19,tested="Yes"}
    am_juniors_20_23 = {name = "Amateur Juniors 20-23", min = 20, max = 23,tested="Yes"}
    am_submasters_33_39 = {name = "Amateur Submasters 33-39", min = 33, max = 39,tested="Yes"}
    am_masters_40_44 = {name = "Amateur Masters 40-44", min = 40, max = 44,tested="Yes"}
    am_masters_45_49 = {name = "Amateur Masters 45-49", min = 45, max = 49,tested="Yes"}
    am_masters_50_54 = {name = "Amateur Masters 50-54", min = 50, max = 54,tested="Yes"}
    am_masters_55_59 = {name = "Amateur Masters 55-59", min = 55, max = 59,tested="Yes"}
    am_masters_60_64 = {name = "Amateur Masters 60-64", min = 60, max = 64,tested="Yes"}
    am_masters_65_69 = {name = "Amateur Masters 65-69", min = 65, max = 69,tested="Yes"}
    am_masters_70_74 = {name = "Amateur Masters 70-74", min = 70, max = 74,tested="Yes"}
    am_masters_75_79 = {name = "Amateur Masters 75-79", min = 75, max = 79,tested="Yes"}
    am_masters_80p = {name = "Amateur Masters 80+", min = 80, max = 999,tested="Yes"}

    am_teen = {name = "Amateur Teen", min = 13, max = 19,tested="Yes"}
    am_masters = {name = "Amateur Masters", min = 40, max = 999,tested="Yes"}


    pro_open = {name = "Pro Open", min = 0, max = 999}
    pro_youth = {name = "Pro Youth", min = 5, max = 12}
    pro_teen_13_15 = {name = "Pro Teen 13-15", min = 13, max = 15}
    pro_teen_16_17 = {name = "Pro Teen 16-17", min = 16, max = 17}
    pro_teen_18_19 = {name = "Pro Teen 18-19", min = 18, max = 19}
    pro_juniors_20_23 = {name = "Pro Juniors 20-23", min = 20, max = 23}
    pro_submasters_33_39 = {name = "Pro Submasters 33-39", min = 33, max = 39}
    pro_masters_40_44 = {name = "Pro Masters 40-44", min = 40, max = 44}
    pro_masters_45_49 = {name = "Pro Masters 45-49", min = 45, max = 49}
    pro_masters_50_54 = {name = "Pro Masters 50-54", min = 50, max = 54}
    pro_masters_55_59 = {name = "Pro Masters 55-59", min = 55, max = 59}
    pro_masters_60_64 = {name = "Pro Masters 60-64", min = 60, max = 64}
    pro_masters_65_69 = {name = "Pro Masters 65-69", min = 65, max = 69}
    pro_masters_70_74 = {name = "Pro Masters 70-74", min = 70, max = 74}
    pro_masters_75_79 = {name = "Pro Masters 75-79", min = 75, max = 79}
    pro_masters_80p = {name = "Pro Masters 80+", min = 80, max = 999}

    pro_teen = {name = "Pro Teen", min = 13, max = 19}
    pro_masters = {name = "Pro Masters", min = 40, max = 999}


    dis_open = {name = "Disabled Open", min = 0, max = 999}
    dis_youth = {name = "Disabled Youth", min = 5, max = 12}
    dis_teen_13_15 = {name = "Disabled Teen 13-15", min = 13, max = 15}
    dis_teen_16_17 = {name = "Disabled Teen 16-17", min = 16, max = 17}
    dis_teen_18_19 = {name = "Disabled Teen 18-19", min = 18, max = 19}
    dis_juniors_20_23 = {name = "Disabled Juniors 20-23", min = 20, max = 23}
    dis_submasters_33_39 = {name = "Disabled Submasters 33-39", min = 33, max = 39}
    dis_masters_40_44 = {name = "Disabled Masters 40-44", min = 40, max = 44}
    dis_masters_45_49 = {name = "Disabled Masters 45-49", min = 45, max = 49}
    dis_masters_50_54 = {name = "Disabled Masters 50-54", min = 50, max = 54}
    dis_masters_55_59 = {name = "Disabled Masters 55-59", min = 55, max = 59}
    dis_masters_60_64 = {name = "Disabled Masters 60-64", min = 60, max = 64}
    dis_masters_65_69 = {name = "Disabled Masters 65-69", min = 65, max = 69}
    dis_masters_70_74 = {name = "Disabled Masters 70-74", min = 70, max = 74}
    dis_masters_75_79 = {name = "Disabled Masters 75-79", min = 75, max = 79}
    dis_masters_80p = {name = "Disabled Masters 80+", min = 80, max = 999}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1980-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["1980-01-01", "9999-01-01"]
    sex = "F"

[exemptions]
    0503 = ["ExemptWeightClassConsistency"]
    0701 = ["ExemptWeightClassConsistency"]
    0703 = ["ExemptWeightClassConsistency"]
    0801 = ["ExemptWeightClassConsistency"]
    0901 = ["ExemptWeightClassConsistency"]
    1001 = ["ExemptWeightClassConsistency"]
    1738 = ["ExemptWeightClassConsistency"]