# Configuration for WRPF-AUS (Australia).

[options]
    require_manual_disambiguation = true

[divisions]
	# OpenLifter-style divisions.
	open = {name="Open", min=0, max=999}
	j8_9 = {name="J8-9", min=8, max=9}
	j10_11 = {name="J10-11", min=10, max=11}
	j12_13 = {name="J12-13", min=12, max=13}
	j14_16 = {name="J14-16", min=14, max=16}
	t14_16 = {name="T14-16", min=14, max=16}
	j17_19 = {name="J17-19", min=17, max=19}
	s17_19 = {name="S17-19", min=17, max=19}
	j20_23 = {name="J20-23", min=20, max=23}
    # "senior" division, not in the rulebook, but they use it
    s24_39 = {name="S24-39", min=24, max=39}
	s35_39 = {name="S35-39", min=35, max=39}
	m40_49 = {name="M40-49", min=40, max=49}
	m50_59 = {name="M50-59", min=50, max=59}
	m60_69 = {name="M60-69", min=60, max=69}
	m70_79 = {name="M70-79", min=70, max=79}
	m80p = {name="M80+", min=80, max=999}
	m60p = {name="M60+", min=60, max=999}
	m70p = {name="M70+", min=70, max=999}

    # More OpenLifter-style divisions, that aren't in the rulebook or the records
    t13_15 = {name="T13-15", min=13, max=15}
    t16_17 = {name="T16-17", min=16, max=17}
    t18_19 = {name="T18-19", min=18, max=19}

    mr_o = {name = "MR-O", min=0, max=999, equipment = ["Raw","Wraps"], sex="M"}
    mr_t = {name = "MR-T", min=14, max=16, equipment = ["Raw","Wraps"], sex="M"}
    mr_y = {name = "MR-Y", min=0, max=13, equipment = ["Raw","Wraps"], sex="M"}
    mr_sj = {name = "MR-SJ", min=17, max=19, equipment = ["Raw","Wraps"], sex="M"}
    mr_j = {name = "MR-J", min=20, max=23, equipment = ["Raw","Wraps"], sex="M"}
    # "senior" division, not in the rulebook, but they use it
    mr_s = {name = "MR-S", min=24, max=39, equipment = ["Raw", "Wraps"], sex="M"}
    mr_m1 = {name = "MR-M1", min=40, max=49, equipment = ["Raw","Wraps"], sex="M"}
    mr_m2 = {name = "MR-M2", min=50, max=59, equipment = ["Raw","Wraps"], sex="M"}
    mr_m3 = {name = "MR-M3", min=60, max=69, equipment = ["Raw","Wraps"], sex="M"}
    mr_m4 = {name = "MR-M4", min=70, max=999, equipment = ["Raw","Wraps"], sex="M"}
    mr_m = {name = "MR-M", min=40, max=999, equipment = ["Raw","Wraps"], sex="M"}

    fr_o = {name = "FR-O", min=0, max=999, equipment = ["Raw","Wraps"], sex="F"}
    fr_t = {name = "FR-T", min=14, max=16, equipment = ["Raw","Wraps"], sex="F"}
    fr_y = {name = "FR-Y", min=0, max=13, equipment = ["Raw","Wraps"], sex="F"}
    fr_sj = {name = "FR-SJ", min=17, max=19, equipment = ["Raw","Wraps"], sex="F"}
    fr_j = {name = "FR-J", min=20, max=23, equipment = ["Raw","Wraps"], sex="F"}
    # "senior" division, not in the rulebook, but they use it
    fr_s = {name = "FR-S", min=24, max=39, equipment = ["Raw", "Wraps"], sex="F"}
    fr_m1 = {name = "FR-M1", min=40, max=49, equipment = ["Raw","Wraps"], sex="F"}
    fr_m2 = {name = "FR-M2", min=50, max=59, equipment = ["Raw","Wraps"], sex="F"}
    fr_m3 = {name = "FR-M3", min=60, max=999, equipment = ["Raw","Wraps"], sex="F"}
    fr_m4 = {name = "FR-M4", min=70, max=999, equipment = ["Raw","Wraps"], sex="F"}
    fr_m = {name = "FR-M", min=40, max=999, equipment = ["Raw","Wraps"], sex="F"}

    msp_o = {name = "MSP-O", min=0, max=999, equipment = "Single-ply", sex = "M"}
    me_o = {name = "ME-O", min=0, max=999, equipment = ["Single-ply","Multi-ply"], sex="M"}
    # "senior" division, not in the rulebook, but they use it
    me_s = {name = "ME-S", min=24, max=39, equipment = ["Single-ply", "Multi-ply"], sex="M"}
    me_m1 = {name = "ME-M1", min=40, max=49, equipment = ["Single-ply","Multi-ply"], sex="M"}
    me_m2 = {name = "ME-M2", min=50, max=59, equipment = ["Single-ply","Multi-ply"], sex="M"}
    me_m = {name = "ME-M", min=40, max=999, equipment = ["Single-ply","Multi-ply"], sex="M"}
    fe_o = {name = "FE-O", min=0, max=999, equipment = ["Single-ply","Multi-ply"], sex="F"}
    fe_s = {name = "FE-S", min=24, max=39, equipment = ["Single-ply", "Multi-ply"], sex="F"}
    fe_t = {name = "FE-T", min=14, max=16, equipment = ["Single-ply","Multi-ply"], sex="F"}
    fe_sj = {name = "FE-SJ", min=17, max=19, equipment = ["Single-ply","Multi-ply"], sex="F"}
    fe_m1 = {name = "FE-M1", min=40, max=49, equipment = ["Single-ply","Multi-ply"], sex="F"}

    # These are used sometimes, also not in rulebook
    master = {name = "Master", min=40, max=999}
    teen = {name = "Teen", min=12, max=19}


[weightclasses.M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["0000-01-01", "9999-12-31"]
    sex = "M"

[weightclasses.F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01", "9999-12-31"]
    sex = "F"

[exemptions]
    2214 = ["ExemptDivision"] # Weird divisions.
