# Configuration for World Powerlifting China.

[divisions]
open = { name="Open", min=0, max=999 }
j18-23 = { name="J18-23", min=18, max=23 }
j19-23 = { name="J19-23", min=19, max=23 }
y14-18 = { name="Y14-18", min=14, max=18 }
m40-44 = { name="M40-44", min=40, max=44 }
m45-49 = { name="M45-49", min=45, max=49 }
m50-54 = { name="M50-54", min=50, max=54 }
m55-59 = { name="M55-59", min=55, max=59 }

mo = {name="M-O", min=0, max=999, sex="M"}
mbl = {name="M-BL", min=0, max=999, sex="M"}
mj18-23 = {name="M-J18-23", min=18, max=23, sex="M"}
mm40-44 = {name="M-M40-44", min=40, max=44, sex="M"}
mm47-53 = {name="M-M47-53", min=47, max=53, sex="M"}

fo = {name="F-O", min=0, max=999, sex="F"}
fbl = {name="F-BL", min=0, max=999, sex="F"}
fj18-23 = {name="F-J18-23", min=18, max=23, sex="F"}

[weightclasses.default_M]
classes = ["62", "69", "77", "85", "94", "105", "120", "120+"]
date_range = ["2018-08-01", "9999-01-01"]
sex = "M"

[weightclasses.default_F]
classes = ["48", "53", "58", "64", "72", "84", "100", "100+"]
date_range = ["2018-08-01", "9999-01-01"]
sex = "F"

[exemptions]
