# Configuration for the SPF.

[options]
    require_manual_disambiguation = true

[rulesets.default]
    ruleset = ["CombineRawAndWraps"]
    date_range = ["0000-01-01", "9999-01-01"]

[divisions]
    open = {name = "Open", min = 0, max = 999}
    preteen = {name = "Pre-Teen", min = 0, max = 12}
    teenage_13_15 = {name = "Teenage 13-15", min = 13, max = 15}
    teenage_16_17 = {name = "Teenage 16-17", min = 16, max = 17}
    teenage_18_19 = {name = "Teenage 18-19", min = 18, max = 19}
    teenage = {name = "Teenage", min = 13, max = 19} # Unspecified age.
    junior_20_23 = {name = "Juniors", min = 20, max = 23}
    submaster = {name = "Submasters", min = 33, max = 39}
    masters_40_44 = {name = "Masters 40-44", min = 40, max = 44}
    masters_45_49 = {name = "Masters 45-49", min = 45, max = 49}
    masters_50_54 = {name = "Masters 50-54", min = 50, max = 54}
    masters_55_59 = {name = "Masters 55-59", min = 55, max = 59}
    masters_60_64 = {name = "Masters 60-64", min = 60, max = 64}
    masters_65_69 = {name = "Masters 65-69", min = 65, max = 69}
    masters_70_74 = {name = "Masters 70-74", min = 70, max = 74}
    masters_75_79 = {name = "Masters 75-79", min = 75, max = 79}
    grandmaster   = {name = "Grand-Masters", min = 80, max = 999}

    # OpenLifter-style.
    t13_15 = {name = "T13-15", min=13, max=15}
    t16_17 = {name = "T16-17", min=16, max=17}
    t18_19 = {name = "T18-19", min=18, max=19}
    j20_23 = {name = "J20-23", min=20, max=23}
    s33_39 = {name = "S33-39", min=33, max=39}
    m40_44 = {name = "M40-44", min=40, max=44}
    m45_49 = {name = "M45-49", min=45, max=49}
    m50_54 = {name = "M50-54", min=50, max=54}
    m55_59 = {name = "M55-59", min=55, max=59}
    m60_64 = {name = "M60-64", min=60, max=64}
    m65_69 = {name = "M65-69", min=65, max=69}
    m70_74 = {name = "M70-74", min=70, max=74}
    m75_79 = {name = "M75-79", min=75, max=79}
    m80_84 = {name = "M80-84", min=80, max=84}
    m80p = {name = "M80+", min=80, max=999}
    fpm = {name = "FPM", min=0, max=999} # Fire Police Military

	adaptive = {name="Adaptive", min=0, max=999}
    disabled = {name="Disabled", min=0, max=999}
    police_fire = {name = "Police and Fire", min = 0, max = 999}
    special_olympics = {name = "Special Olympics", min = 0, max = 999}
    crossfit = {name = "Crossfit", min = 0, max = 999}

[weightclasses.default_M]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","110","118","125","140","140+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","110","118","90+","110+","140+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "F"

[exemptions]
    1628 = ["ExemptWeightClassConsistency"]  # Reebok Record Breakers.
    1752 = ["ExemptWeightClassConsistency"]  # Reebok Record Breakers.
    1846 = ["ExemptWeightClassConsistency"]  # Slingshot Record Breakers.
    1946 = ["ExemptWeightClassConsistency"]  # Slingshot Record Breakers.
    2135 = ["ExemptWeightClassConsistency"]  # Missing bodyweight/weightclass data for some lifters.
    2430 = ["ExemptWeightClassConsistency"]  # Missing bodyweight/weightclass data for a lifter.
    2505 = ["ExemptWeightClassConsistency"]  # Missing bodyweight/weightclass data for a lifter.
