# Configuration for UkrainePF
[options]
    require_manual_disambiguation = true

[divisions]
    open = {name ="Open",min=0,max=999}
    disabled = {name ="Disabled",min=0,max=999}
    student = {name ="Student",min=0,max=999}
    juniors = {name = "Juniors",min=0,max=22.5}
    subjuniors = {name = "Sub-Juniors",min=0,max=17.5}
    masters1 = {name = "Masters 1",min=39.5,max=48.5}
    masters2 = {name = "Masters 2",min=49.5,max=58.5}
    masters3 = {name = "Masters 3",min=59.5,max=68.5}
    masters4 = {name = "Masters 4",min=69.5,max=999}
    teen1214 = {name = "Teen 12-14",min=12,max=14}
    teen1415 = {name = "Teen 14-15",min=14,max=15}
    teen1516 = {name = "Teen 15-16",min=15,max=16}
    teen1718 = {name = "Teen 17-18",min=17,max=18}
    teen1618 = {name = "Teen 16-18",min=16,max=18}
    youth1215 = {name = "Youth 12-15",min=12,max=15}
    youth1015 = {name = "Youth 10-15",min=10,max=15}
    youth1113 = {name = "Youth 11-13",min=11,max=13}

[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["47","52","57","63","69","76","84","84+"]
    date_range=["2021-01-01","9999-01-01"]
    sex = "F"

[weightclasses.year2020_F]
    classes = ["47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","2020-12-31"]
    sex = "F"

[weightclasses.junior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["Juniors"]

[weightclasses.subjunior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["Sub-Juniors","Teen 12-14","Teen 15-16","Teen 17-18"]


[weightclasses.junior_F]
    classes = ["43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"
    divisions = ["Juniors"]

[weightclasses.subjunior_F]
    classes = ["43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"
    divisions = ["Sub-Juniors","Teen 12-14","Teen 15-16","Teen 17-18"]

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"

[weightclasses.disabled_M]
    classes = ["48","52","56","60","67.5","75","82.5","90","100","100+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"
    divisions = ["Disabled"]

[weightclasses.disabled_F]
    classes = ["40","44","48","52","56","60","67.5","75","82.5","82.5+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"
    divisions = ["Disabled"]

[weightclasses.oldsubjunior_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","100+"]
    date_range = ["0000-01-01","2003-12-31"]
    sex = "M"
    divisions = ["Sub-Juniors"]

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"

[weightclasses.oldsubjunior_F]
    classes = ["36","40","44","48","52","56","60","67.5","75","75+"]
    date_range = ["0000-01-01","2003-12-31"]
    sex = "F"
    divisions = ["Sub-Juniors"]

[exemptions]
    9101 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    9205 = ["ExemptWeightClassConsistency"] # 44kg & 48kg men
    9305 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    9405 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    9507 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    9606 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    9702 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    9802 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    9902 = ["ExemptWeightClassConsistency"] # 44kg & 48kg men
    9905 = ["ExemptWeightClassConsistency"] # No 40kg
    0003 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    0103 = ["ExemptWeightClassConsistency"] # 44kg & 48kg men
    0204 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    0303 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    0608 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    0901 = ["ExemptWeightClassConsistency"] # No 52kg
    1001 = ["ExemptWeightClassConsistency"] # Extra SJ Classes, 100+ & 82.5+
    1010 = ["ExemptWeightClassConsistency"] # 44kg & 48kg open men
    1012 = ["ExemptWeightClassConsistency"] # Didn't use 52kg class
    1013 = ["ExemptWeightClassConsistency"] # 44kg & 48kg open men
    1102 = ["ExemptWeightClassConsistency"] # 47 & 49kg men
    1110 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1113 = ["ExemptWeightClassConsistency"] # 43 & 49kg men
    1115 = ["ExemptWeightClassConsistency"] # 46kg open men
    1203 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1204 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1208 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1216 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1217 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1218 = ["ExemptWeightClassConsistency"] # 46 & 49kg men
    1219 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1220 = ["ExemptWeightClassConsistency"] # 46 & 49kg men
    1224 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1225 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1226 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1301 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1305 = ["ExemptWeightClassConsistency"] # 46 & 49kg men
    1316 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1317 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1318 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1319 = ["ExemptWeightClassConsistency"] # 49kg men
    1320 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1321 = ["ExemptWeightClassConsistency"] # 46 & 49kg men
    1323 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1327 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1404 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1405 = ["ExemptWeightClassConsistency","ExemptDivision"]
    1410 = ["ExemptWeightClassConsistency","ExemptDivision"]
    1411 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1412 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1413 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1414 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1415 = ["ExemptWeightClassConsistency"] # 46 & 49kg men
    1416 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1418 = ["ExemptWeightClassConsistency"] # Extra SJ Classes, missing womens classes
    1420 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1504 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1517 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1604 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1606 = ["ExemptWeightClassConsistency"] # 46 & 49kg men
    1609 = ["ExemptWeightClassConsistency"] # 43kg men
    1704 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
