[divisions]
#Intentionally blank  

[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["0000-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["47","52","57","63","69","76","84","84+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "F"


[exemptions]
	2202 = ["ExemptWeightClassConsistency"] # IWF categories instead of IPF ones
    2403 = ["ExemptWeightClassConsistency"] # Limited categories.
    2404 = ["ExemptWeightClassConsistency"] # Limited categories.
    2406 = ["ExemptWeightClassConsistency"] # Limited categories.
    2506 = ["ExemptWeightClassConsistency"] # Limited categories.
    2507 = ["ExemptWeightClassConsistency"] # Limited categories.
    2509 = ["ExemptWeightClassConsistency"] # Limited categories.
    2510 = ["ExemptWeightClassConsistency"] # Limited categories.