# Configuration for THSPA.

[divisions]
    # The main division used for almost everything.
    boys = {name="Boys", min=13, max=19, sex="M"}

    freshmen = {name="Freshmen", min=13, max=15, sex="M"}
    jv = {name="Junior Varsity", min=13, max=19, sex="M"}
    v = {name="Varsity", min=13, max=19, sex="M"}

    div1 = {name="Div 1", min=13, max=19, sex="M"}
    div2 = {name="Div 2", min=13, max=19, sex="M"}
    div3 = {name="Div 3", min=13, max=19, sex="M"}

    # Sometimes girls are listed in THSPA for some reason...
    girls = {name="Girls", min=13, max=19, sex="F"}

# THSPA uses pounds classes with exact pound values.
[weightclasses.default_M]
    classes = ["51.71","55.79","59.87","67.13","74.84","82.1","89.81","99.79","109.77","124.74","139.71","139.71+"]
    date_range=["2021-01-01","9999-01-01"]
    sex = "M"

[weightclasses.year2020_M]
    classes = ["51.71","55.79","59.87","67.13","74.84","82.1","89.81","99.79","109.77","124.74","124.74+"]
    date_range=["0000-01-01","2020-12-31"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44.23","47.85","51.94","56.02","60.1","67.36","75.07","82.33","90.04","100.02","117.71","100.02+","117.71+"]
    date_range=["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]
