[options]
    require_manual_disambiguation = true

[divisions]
    open = {name ="Open",min=0,max=999}
    blind = {name ="Blind",min=0,max=999}
    juniors = {name = "Juniors",min=0,max=22.5}
    subjuniors = {name = "Sub-Juniors",min=0,max=17.5}
    1318 = {name = "13-18",min=13,max=18}
    teen = {name = "Teen", min=13, max=19}
    masters1 = {name = "Masters 1",min=39.5,max=48.5}
    masters2 = {name = "Masters 2",min=49.5,max=58.5}
    masters3 = {name = "Masters 3",min=59.5,max=68.5}
    masters4 = {name = "Masters 4",min=69.5,max=999}
    paralympics = {name = "Paralympics",min=0,max=999}
    paralympic_jr = {name = "Paralympic Juniors",min=0,max=22.5}
    youth = {name = "Youth", min=5, max=16}

[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"

[weightclasses.subjunior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["Sub-Juniors","13-18","Teen"]


[weightclasses.junior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["Juniors"]

[weightclasses.junior_F]
    classes = ["43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"
    divisions = ["Juniors"]

[weightclasses.subjunior_F]
    classes = ["43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"
    divisions = ["Sub-Juniors","13-18","Teen"]

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"

[weightclasses.old_subjunior_M]
    classes = ["48","52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"
    divisions = ["Sub-Juniors"]

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"

[weightclasses.old_subjunior_F]
    classes = ["40","44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"
    divisions = ["Sub-Juniors"]

[weightclasses.para_F]
    classes = ["40","44","48","52","56","60","67.5","75","82.5","82.5+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"
    divisions = ["Paralympics"]

[weightclasses.para_M]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","100+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"
    divisions = ["Paralympics"]

[exemptions]
    8803 = ["ExemptWeightClassConsistency"] # Men's 110+
    8902 = ["ExemptWeightClassConsistency"] # No weightclasses for Women
    9001 = ["ExemptDivision"]
    9104 = ["ExemptWeightClassConsistency"] # No 48kg SJ men
    9403 = ["ExemptWeightClassConsistency"] # No weightclasses
    9503 = ["ExemptDivision"] # Only Masters 1 and Masters 2
    9905 = ["ExemptDivision"] # Only Masters 1 and Masters 2
    0004 = ["ExemptWeightClassConsistency"] # No weightclasses for Women
    0006 = ["ExemptWeightClassConsistency"] # Women's 82.5+, Men's 110+
    0007 = ["ExemptWeightClassConsistency"] # No weightclasses for Women
    0008 = ["ExemptWeightClassConsistency"] # No weightclasses for Women
    0011 = ["ExemptDivision"] # Only Masters 1 and Masters 2
    0103 = ["ExemptWeightClassConsistency"] # Top SJ class is 110
    0109 = ["ExemptWeightClassConsistency"] # No weightclasses for Women
    0110 = ["ExemptWeightClassConsistency"] # No weightclasses for Women
    0111 = ["ExemptWeightClassConsistency"] # No weightclasses for Women
    0207 = ["ExemptWeightClassConsistency"]
    0208 = ["ExemptWeightClassConsistency"] # Women's 82.5+
    0209 = ["ExemptWeightClassConsistency"] # No weightclasses for Women
    0210 = ["ExemptWeightClassConsistency"] # No weightclasses for Women
    0211 = ["ExemptWeightClassConsistency"] # No weightclasses for Women
    0212 = ["ExemptWeightClassConsistency"] # No weightclasses for Women
    0310 = ["ExemptWeightClassConsistency"]
    0311 = ["ExemptWeightClassConsistency"] # No weightclasses for Women
    0314 = ["ExemptWeightClassConsistency"] # Fewer weightclasses for Women
    0319 = ["ExemptWeightClassConsistency"] # No weightclasses for Women
    0320 = ["ExemptWeightClassConsistency"] # No weightclasses for Women
    0321 = ["ExemptWeightClassConsistency"] # No weightclasses for Women
    0412 = ["ExemptWeightClassConsistency"] # Fewer weight classes
    0418 = ["ExemptWeightClassConsistency"] # No weightclasses for Jr Women
    0510 = ["ExemptWeightClassConsistency"] # No SJ 48
    0512 = ["ExemptWeightClassConsistency"] # No Para 48
    0611 = ["ExemptWeightClassConsistency"] # Youth Classes
    0630 = ["ExemptWeightClassConsistency"] # Youth Classes
    0723 = ["ExemptWeightClassConsistency"] # 56 Women in 60 class
    0804 = ["ExemptWeightClassConsistency"]
    0805 = ["ExemptWeightClassConsistency"]
    0807 = ["ExemptWeightClassConsistency"]
    0808 = ["ExemptWeightClassConsistency"]
    0811 = ["ExemptWeightClassConsistency"]
    0812 = ["ExemptWeightClassConsistency"]
    0814 = ["ExemptWeightClassConsistency"] # No men's 52
    0824 = ["ExemptWeightClassConsistency"] # No men's 52
    0901 = ["ExemptWeightClassConsistency"]
    0903 = ["ExemptWeightClassConsistency"]
    0910 = ["ExemptWeightClassConsistency"]
    0911 = ["ExemptWeightClassConsistency"]
    0914 = ["ExemptWeightClassConsistency"] # Fewer weight classes
    0916 = ["ExemptWeightClassConsistency"] # Fewer weight classes
    0923 = ["ExemptWeightClassConsistency"] # Fewer weight classes
    0931 = ["ExemptWeightClassConsistency"] # No men's 52
    1001 = ["ExemptWeightClassConsistency"]
    1002 = ["ExemptWeightClassConsistency"]
    1005 = ["ExemptWeightClassConsistency"] # Fewer weight classes
    1006 = ["ExemptWeightClassConsistency"] # Fewer weight classes for raw
    1007 = ["ExemptWeightClassConsistency"] # No women's 44
    1010 = ["ExemptWeightClassConsistency"] # Fewer weight classes for raw
    1011 = ["ExemptWeightClassConsistency"] # Fewer weight classes for raw
    1013 = ["ExemptWeightClassConsistency"] # Fewer weight classes for raw
    1014 = ["ExemptWeightClassConsistency"] # Fewer weight classes for raw
    1018 = ["ExemptWeightClassConsistency"] # 125, 125+ Sub-Juniors
    1024 = ["ExemptWeightClassConsistency"] # Fewer weight classes for raw
    1026 = ["ExemptWeightClassConsistency"] # No men's 52
    1028 = ["ExemptWeightClassConsistency"] # Fewer weight classes for raw
    1029 = ["ExemptWeightClassConsistency"] # No 44 class
    1030 = ["ExemptWeightClassConsistency"] # Fewer weight classes for raw
    1106 = ["ExemptWeightClassConsistency"]
    1107 = ["ExemptWeightClassConsistency"]
    1120 = ["ExemptWeightClassConsistency"] # Youth Classes
    1121 = ["ExemptWeightClassConsistency"] # Youth Classes
    1125 = ["ExemptWeightClassConsistency"] # Youth Classes
    1126 = ["ExemptWeightClassConsistency"] # Youth Classes
    1203 = ["ExemptWeightClassConsistency"]
    1204 = ["ExemptWeightClassConsistency"] # Youth Classes
    1221 = ["ExemptWeightClassConsistency"] # Youth Classes
    1236 = ["ExemptWeightClassConsistency"] # Jr/SJr Classes
    1238 = ["ExemptWeightClassConsistency"] # Jr/SJr Classes
    1301 = ["ExemptWeightClassConsistency"]
    1302 = ["ExemptWeightClassConsistency"]
    1303 = ["ExemptWeightClassConsistency"]
    1304 = ["ExemptWeightClassConsistency"]
    1306 = ["ExemptWeightClassConsistency"]
    1307 = ["ExemptWeightClassConsistency"]
    1309 = ["ExemptWeightClassConsistency"]
    1310 = ["ExemptWeightClassConsistency"]
    1313 = ["ExemptWeightClassConsistency"] # Youth Classes
    1314 = ["ExemptWeightClassConsistency"] # Youth Classes
    1320 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1327 = ["ExemptWeightClassConsistency"] # Youth Classes
    1328 = ["ExemptWeightClassConsistency"] # Jr/SJr Classes
    1330 = ["ExemptWeightClassConsistency"] # Youth Classes
    1337 = ["ExemptWeightClassConsistency"] # Jr/SJr Classes
    1339 = ["ExemptWeightClassConsistency"] # Jr/SJr Classes
    1340 = ["ExemptWeightClassConsistency"] # Jr/SJr Classes
    1342 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1345 = ["ExemptWeightClassConsistency"] # Jr/SJr Classes
    1346 = ["ExemptWeightClassConsistency"] # Jr/SJr Classes
    1403 = ["ExemptWeightClassConsistency"]
    1406 = ["ExemptWeightClassConsistency"]
    1408 = ["ExemptWeightClassConsistency"]
    1411 = ["ExemptWeightClassConsistency"]
    1417 = ["ExemptWeightClassConsistency"]
    1428 = ["ExemptWeightClassConsistency"] # Youth Classes
    1432 = ["ExemptWeightClassConsistency"] # Youth Classes
    1434 = ["ExemptWeightClassConsistency"] # Youth Classes
    1435 = ["ExemptWeightClassConsistency"] # Youth Classes
    1441 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1442 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1444 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1447 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1449 = ["ExemptWeightClassConsistency"] # Jr/SJr Classes
    1450 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1451 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1453 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1457 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1505 = ["ExemptWeightClassConsistency"]
    1509 = ["ExemptWeightClassConsistency"]
    1510 = ["ExemptWeightClassConsistency"]
    1523 = ["ExemptWeightClassConsistency"] # Youth Classes
    1528 = ["ExemptWeightClassConsistency"] # Youth Classes
    1529 = ["ExemptWeightClassConsistency"] # Youth Classes
    1532 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1533 = ["ExemptWeightClassConsistency"] # Youth Classes
    1534 = ["ExemptWeightClassConsistency"] # Youth Classes
    1535 = ["ExemptWeightClassConsistency"] # Youth Classes
    1537 = ["ExemptWeightClassConsistency"] # Jr/SJr Classes
    1607 = ["ExemptWeightClassConsistency"]
    1621 = ["ExemptWeightClassConsistency"] # Youth Classes
    1631 = ["ExemptWeightClassConsistency"] # They stuffed up the womens classes
    1642 = ["ExemptWeightClassConsistency"] # Jr/SJr Classes
    1643 = ["ExemptWeightClassConsistency"] # Jr/SJr Classes
    1645 = ["ExemptWeightClassConsistency"] # Jr/SJr Classes
    1705 = ["ExemptWeightClassConsistency"]
    1746 = ["ExemptWeightClassConsistency"] # Jr/SJr Classes
    1804 = ["ExemptWeightClassConsistency"]
    1920 = ["ExemptWeightClassConsistency"] # Masters have no weight class
    1876 = ["ExemptWeightClassConsistency"] # Extra SJ Classes
    1922 = ["ExemptWeightClassConsistency"]
    1919 = ["ExemptWeightClassConsistency"]
    1924 = ["ExemptWeightClassConsistency"]
    1937 = ["ExemptWeightClassConsistency"]
    1956 = ["ExemptWeightClassConsistency"]
    1961 = ["ExemptWeightClassConsistency"] # Masters have no weight class
    1813 = ["ExemptWeightClassConsistency"] # 53s in Open
