# Configuration for GPC.

[rulesets.default]
    ruleset = ["CombineRawAndWraps", "CombineSingleAndMulti"]
    date_range = ["0000-01-01", "9999-01-01"]

[divisions]
    or = {name ="O",min=0,max=999}
    j = {name ="J",min=20,max=23}
    j20_23 = {name ="J20-23",min=20,max=23}
    t13_16 = {name ="T13-16",min=13,max=16}
    t17_19 = {name ="T17-19",min=17,max=19}
    m40_49 = {name ="M40-49",min=40,max=49}
    m50_59 = {name ="M50-59",min=50,max=59}
    m60_69 = {name ="M60-69",min=60,max=69}
    m70_79 = {name ="M70-79",min=70,max=79}

    t13_15 = {name ="T13-15",min=13,max=15}
    t16_17 = {name ="T16-17",min=16,max=17}
    t18_19 = {name ="T18-19",min=18,max=19}
    m40_44 = {name ="M40-44",min=40,max=44}
    m45_49 = {name ="M45-49",min=45,max=49}
    m50_54 = {name ="M50-54",min=50,max=54}
    m55_59 = {name ="M55-59",min=54,max=59}
    m60_64 = {name ="M60-64",min=60,max=64}
    m65_69 = {name ="M65-69",min=65,max=69}
    m70_74 = {name ="M70-74",min=70,max=74}
    m75_79 = {name ="M75-79",min=74,max=79}

	# Special divisions for special competitions.
	dorast = {name="Dorast",min=0,max=19}  # Sub-Juniors, effectively.
	m40_54 = {name="M40-54",min=40,max=54}
	m55p = {name="M55+",min=55,max=999}

[weightclasses.default_M]
    classes = ["56","60","67.5","75","82.5","90","100","110","125","140","125+","140+"]
    date_range = ["2016-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","110","110+"]
    date_range = ["2016-01-01","9999-01-01"]
    sex = "F"

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2015-12-31"]
    sex = "F"

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","125+","140+"]
    date_range = ["0000-01-01","2015-12-31"]
    sex = "M"

[exemptions]
    2101 = ["ExemptWeightClassConsistency"] # 90/90+
