# Configuration for World Powerlifting.
# https://cdn.worldpowerlifting.com/wp-content/uploads/2019/07/world-powerlifting-rules.pdf

[divisions]
    # Over 14 years on the day of competition (assuming they meant >=).
    open = {name="Open", min=14, max=999}

    # 14 years or more on the day of competition, up to (including) year turning 18.
    youth = {name="Youth", min=14, max=17.5}

    # 18 years or more, up to (including) year turning 23.
    juniors = {name="Juniors", min=18, max=22.5}

    # Masters classes are entirely Birth-Year based.
    masters40_44 = {name="Masters 40-44", min=39.5, max=43.5}
    masters45_49 = {name="Masters 45-49", min=44.5, max=48.5}
    masters50_54 = {name="Masters 50-54", min=49.5, max=53.5}
    masters55_59 = {name="Masters 55-59", min=54.5, max=58.5}
    masters60_64 = {name="Masters 60-64", min=59.5, max=63.5}
    masters65_69 = {name="Masters 65-69", min=64.5, max=68.5}
    masters70_74 = {name="Masters 70-74", min=69.5, max=73.5}
    masters75_79 = {name="Masters 75-79", min=74.5, max=78.5}
    masters80s = {name="Masters 80+", min=79.5, max=999}

    # OpenLifter-style names.
    j10_12 = {name = "J10-12", min=10, max=12}
    j13_15 = {name = "J13-15", min=13, max=15}
    j16_17 = {name = "J16-17", min=16, max=17}
    j18_19 = {name = "J18-19", min=18, max=19}
    j20_23 = {name = "J20-23", min=20, max=23}
    s35_39 = {name = "S35-39", min=35, max=39}
    m40_44 = {name = "M40-44", min=40, max=44}
    m45_49 = {name = "M45-49", min=45, max=49}
    m50_54 = {name = "M50-54", min=50, max=54}
    m55_59 = {name = "M55-59", min=55, max=59}
    m60_64 = {name = "M60-64", min=60, max=64}
    m65_69 = {name = "M65-69", min=65, max=69}
    m70_74 = {name = "M70-74", min=70, max=74}
    m75_79 = {name = "M75-79", min=75, max=79}
    m80_84 = {name = "M80-84", min=80, max=84}
    m80p = {name = "M80+", min=80, max=999}

    # Odd divisions.
    s33_39 = {name = "S33-39", min=33, max=39}

[weightclasses.default_M]
    classes = ["62", "69", "77", "85", "94", "105", "120", "120+"]
    date_range = ["2018-08-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["48", "53", "58", "64", "72", "84", "100", "100+"]
    date_range = ["2018-08-01", "9999-01-01"]
    sex = "F"

[exemptions]
