# Configuration for GPC-Brasil.

[rulesets.default]
    ruleset = ["CombineRawAndWraps", "CombineSingleAndMulti"]
    date_range = ["0000-01-01", "9999-01-01"]

[divisions]
    mo = {name ="MO", min=0, max=999, sex="M", equipment = ["Raw","Wraps"]}
    fo = {name ="FO", min=0, max=999, sex="F", equipment = ["Raw","Wraps"]}
    mt1315 = {name ="MT 13-15", min=13, max=15, sex="M", equipment = ["Raw","Wraps"]}
    ft1315 = {name ="FT 13-15", min=13, max=15, sex="F", equipment = ["Raw","Wraps"]}
    mt1617 = {name ="MT 16-17", min=16, max=17, sex="M", equipment = ["Raw","Wraps"]}
    ft1617 = {name ="FT 16-17", min=16, max=17, sex="F", equipment = ["Raw","Wraps"]}
    mt1819 = {name ="MT 18-19", min=18, max=19, sex="M", equipment = ["Raw","Wraps"]}
    ft1819 = {name ="FT 18-19", min=18, max=19, sex="F", equipment = ["Raw","Wraps"]}
    mj = {name ="MJ", min=20, max=23, sex="M", equipment = ["Raw","Wraps"]}
    fj = {name ="FJ", min=20, max=23, sex="F", equipment = ["Raw","Wraps"]}
    m4044 = {name ="M 40-44", min=40, max=44, sex="M", equipment = ["Raw","Wraps"]}
    f4044 = {name ="F 40-44", min=40, max=44, sex="F", equipment = ["Raw","Wraps"]}
    m4549 = {name ="M 45-49", min=45, max=49, sex="M", equipment = ["Raw","Wraps"]}
    f4549 = {name ="F 45-49", min=45, max=49, sex="F", equipment = ["Raw","Wraps"]}
    m5054 = {name ="M 50-54", min=50, max=54, sex="M", equipment = ["Raw","Wraps"]}
    f5054 = {name ="F 50-54", min=50, max=54, sex="F", equipment = ["Raw","Wraps"]}
    m5559 = {name ="M 55-59", min=55, max=59, sex="M", equipment = ["Raw","Wraps"]}
    f5559 = {name ="F 55-59", min=55, max=59, sex="F", equipment = ["Raw","Wraps"]}
    m6064 = {name ="M 60-64", min=60, max=64, sex="M", equipment = ["Raw","Wraps"]}
    f6064 = {name ="F 60-64", min=60, max=64, sex="F", equipment = ["Raw","Wraps"]}
    m6569 = {name ="M 65-69", min=65, max=69, sex="M", equipment = ["Raw","Wraps"]}
    f6569 = {name ="F 65-69", min=65, max=69, sex="F", equipment = ["Raw","Wraps"]}
    m7074 = {name ="M 70-74", min=70, max=74, sex="M", equipment = ["Raw","Wraps"]}
    f7074 = {name ="F 70-74", min=70, max=74, sex="F", equipment = ["Raw","Wraps"]}
    m7579 = {name ="M 75-79", min=75, max=79, sex="M", equipment = ["Raw","Wraps"]}
    f7579 = {name ="F 75-79", min=75, max=79, sex="F", equipment = ["Raw","Wraps"]}

    m4080 = {name ="M 40-80", min=40, max=80, sex="M", equipment = ["Raw","Wraps"]}
    f4080 = {name ="F 40-80", min=40, max=80, sex="F", equipment = ["Raw","Wraps"]}
    moes = {name ="MO ES", min=0, max=999, sex="M", equipment = ["Raw","Wraps"]} #Special Olympics?
    foes = {name ="FO ES", min=0, max=999, sex="F", equipment = ["Raw","Wraps"]}
    mjes = {name ="MJ ES", min=20, max=23, sex="M", equipment = ["Raw","Wraps"]}
    fjes = {name ="FJ ES", min=20, max=23, sex="F", equipment = ["Raw","Wraps"]}
    m4044es = {name ="M 40-44 ES", min=40, max=44, sex="M", equipment = ["Raw","Wraps"]}
    f4044es = {name ="F 40-44 ES", min=40, max=44, sex="F", equipment = ["Raw","Wraps"]}
    m6569es = {name ="M 65-69 ES", min=65, max=69, sex="M", equipment = ["Raw","Wraps"]}
    f6569es = {name ="F 65-69 ES", min=65, max=69, sex="F", equipment = ["Raw","Wraps"]}


    moeq = {name ="MO EQ", min=0, max=999, sex="M", equipment = ["Single-ply","Multi-ply"]}
    foeq = {name ="FO EQ", min=0, max=999, sex="F", equipment = ["Single-ply","Multi-ply"]}
    mt1617eq = {name ="MT 16-17 EQ", min=16, max=17, sex="M", equipment = ["Single-ply","Multi-ply"]}
    ft1617eq = {name ="FT 16-17 EQ", min=16, max=17, sex="F", equipment = ["Single-ply","Multi-ply"]}
    mt1819eq = {name ="MT 18-19 EQ", min=18, max=19, sex="M", equipment = ["Single-ply","Multi-ply"]}
    ft1819eq = {name ="FT 18-19 EQ", min=18, max=19, sex="F", equipment = ["Single-ply","Multi-ply"]}
    mjeq = {name ="MJ EQ", min=20, max=23, sex="M", equipment = ["Single-ply","Multi-ply"]}
    fjeq = {name ="FJ EQ", min=20, max=23, sex="F", equipment = ["Single-ply","Multi-ply"]}
    m4044eq = {name ="M 40-44 EQ", min=40, max=44, sex="M", equipment = ["Single-ply","Multi-ply"]}
    f4044eq = {name ="F 40-44 EQ", min=40, max=44, sex="F", equipment = ["Single-ply","Multi-ply"]}
    m4549eq = {name ="M 45-49 EQ", min=45, max=49, sex="M", equipment = ["Single-ply","Multi-ply"]}
    f4549eq = {name ="F 45-49 EQ", min=45, max=49, sex="F", equipment = ["Single-ply","Multi-ply"]}
    m5054eq = {name ="M 50-54 EQ", min=50, max=54, sex="M", equipment = ["Single-ply","Multi-ply"]}
    f5054eq = {name ="F 50-54 EQ", min=50, max=54, sex="F", equipment = ["Single-ply","Multi-ply"]}
    m5559eq = {name ="M 55-59 EQ", min=55, max=59, sex="M", equipment = ["Single-ply","Multi-ply"]}
    f5559eq = {name ="F 55-59 EQ", min=55, max=59, sex="F", equipment = ["Single-ply","Multi-ply"]}
    m6064eq = {name ="M 60-64 EQ", min=60, max=64, sex="M", equipment = ["Single-ply","Multi-ply"]}
    f6064eq = {name ="F 60-64 EQ", min=60, max=64, sex="F", equipment = ["Single-ply","Multi-ply"]}
    m6569eq = {name ="M 65-69 EQ", min=65, max=69, sex="M", equipment = ["Single-ply","Multi-ply"]}
    f6569eq = {name ="F 65-69 EQ", min=65, max=69, sex="F", equipment = ["Single-ply","Multi-ply"]}
    m7074eq = {name ="M 70-74 EQ", min=70, max=74, sex="M", equipment = ["Single-ply","Multi-ply"]}
    f7074eq = {name ="F 70-74 EQ", min=70, max=74, sex="F", equipment = ["Single-ply","Multi-ply"]}
    m7579eq = {name ="M 75-79 EQ", min=75, max=79, sex="M", equipment = ["Single-ply","Multi-ply"]}

[weightclasses.default_M]
    classes = ["56","60","67.5","75","82.5","90","100","110","125","140","125+","140+"]
    date_range = ["2016-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","110","110+"]
    date_range = ["2016-01-01","9999-01-01"]
    sex = "F"

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2015-12-31"]
    sex = "F"

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","125+","140+"]
    date_range = ["0000-01-01","2015-12-31"]
    sex = "M"

[exemptions]
