# Configuration for the TPSSF, taken from USAPL.

[divisions]
    # Official divisions, Raw Men.
    mro = {name="MR-O", min=14, max=999, sex="M", equipment="Raw"}
    mry = {name="MR-Y", min=8, max=13, sex="M", equipment="Raw"}
    mry1 = {name="MR-Y1", min=8, max=9, sex="M", equipment="Raw"}
    mry2 = {name="MR-Y2", min=10, max=11, sex="M", equipment="Raw"}
    mry3 = {name="MR-Y3", min=12, max=13, sex="M", equipment="Raw"}
    mrt = {name="MR-T", min=14, max=19, sex="M", equipment="Raw"}
    mrt1 = {name="MR-T1", min=14, max=15, sex="M", equipment="Raw"}
    mrt2 = {name="MR-T2", min=16, max=17, sex="M", equipment="Raw"}
    mrt3 = {name="MR-T3", min=18, max=19, sex="M", equipment="Raw"}
    mrtj = {name="MR-TJ", min=14, max=23, sex="M", equipment="Raw"}
    mrsj = {name="MR-SJ", min=14, max=18, sex="M", equipment="Raw"}
    mrjr = {name="MR-Jr", min=18, max=23, sex="M", equipment="Raw"}
    mrm1a = {name="MR-M1a", min=39.5, max=43.5, sex="M", equipment="Raw"}
    mrm1b = {name="MR-M1b", min=44.5, max=48.5, sex="M", equipment="Raw"}
    mrm2a = {name="MR-M2a", min=49.5, max=53.5, sex="M", equipment="Raw"}
    mrm2b = {name="MR-M2b", min=54.5, max=58.5, sex="M", equipment="Raw"}
    mrm3a = {name="MR-M3a", min=59.5, max=63.5, sex="M", equipment="Raw"}
    mrm3b = {name="MR-M3b", min=64.5, max=68.5, sex="M", equipment="Raw"}
    mrm4a = {name="MR-M4a", min=69.5, max=73.5, sex="M", equipment="Raw"}
    mrm4b = {name="MR-M4b", min=74.5, max=78.5, sex="M", equipment="Raw"}
    mrm5a = {name="MR-M5a", min=79.5, max=83.5, sex="M", equipment="Raw"}
    mrm5b = {name="MR-M5b", min=84.5, max=88.5, sex="M", equipment="Raw"}
    mrm6a = {name="MR-M6a", min=89.5, max=93.5, sex="M", equipment="Raw"}
    mrm6b = {name="MR-M6b", min=94.5, max=98.5, sex="M", equipment="Raw"}
    mrm = {name="MR-M", min=39.5, max=999, sex="M", equipment="Raw"}
    mrm1 = {name="MR-M1", min=39.5, max=48.5, sex="M", equipment="Raw"}
    mrm2 = {name="MR-M2", min=49.5, max=58.5, sex="M", equipment="Raw"}
    mrm3 = {name="MR-M3", min=59.5, max=68.5, sex="M", equipment="Raw"}
    mrm4 = {name="MR-M4", min=69.5, max=78.5, sex="M", equipment="Raw"}
    mrm5 = {name="MR-M5", min=79.5, max=88.5, sex="M", equipment="Raw"}
    mrm6 = {name="MR-M6", min=89.5, max=98.5, sex="M", equipment="Raw"}
    mrm7 = {name="MR-M7", min=99.5, max=999, sex="M", equipment="Raw"}
    mrg = {name="MR-G", min=0, max=999, sex="M", equipment="Raw", place="G"}

    # Official divisions, Raw Women.
    fro = {name="FR-O", min=14, max=999, sex="F", equipment="Raw"}
    fry = {name="FR-Y", min=8, max=13, sex="F", equipment="Raw"}
    fry1 = {name="FR-Y1", min=8, max=9, sex="F", equipment="Raw"}
    fry2 = {name="FR-Y2", min=10, max=11, sex="F", equipment="Raw"}
    fry3 = {name="FR-Y3", min=12, max=13, sex="F", equipment="Raw"}
    frt = {name="FR-T", min=14, max=19, sex="F", equipment="Raw"}
    frt1 = {name="FR-T1", min=14, max=15, sex="F", equipment="Raw"}
    frt2 = {name="FR-T2", min=16, max=17, sex="F", equipment="Raw"}
    frt3 = {name="FR-T3", min=18, max=19, sex="F", equipment="Raw"}
    frtj = {name="FR-TJ", min=14, max=23, sex="F", equipment="Raw"}
    frsj = {name="FR-SJ", min=14, max=18, sex="F", equipment="Raw"}
    frjr = {name="FR-Jr", min=18, max=23, sex="F", equipment="Raw"}
    frm1a = {name="FR-M1a", min=39.5, max=43.5, sex="F", equipment="Raw"}
    frm1b = {name="FR-M1b", min=44.5, max=48.5, sex="F", equipment="Raw"}
    frm2a = {name="FR-M2a", min=49.5, max=53.5, sex="F", equipment="Raw"}
    frm2b = {name="FR-M2b", min=54.5, max=59.5, sex="F", equipment="Raw"}
    frm3a = {name="FR-M3a", min=59.5, max=63.5, sex="F", equipment="Raw"}
    frm3b = {name="FR-M3b", min=64.5, max=68.5, sex="F", equipment="Raw"}
    frm4a = {name="FR-M4a", min=69.5, max=73.5, sex="F", equipment="Raw"}
    frm4b = {name="FR-M4b", min=74.5, max=78.5, sex="F", equipment="Raw"}
    frm5a = {name="FR-M5a", min=79.5, max=83.5, sex="F", equipment="Raw"}
    frm5b = {name="FR-M5b", min=84.5, max=88.5, sex="F", equipment="Raw"}
    frm6a = {name="FR-M6a", min=89.5, max=93.5, sex="F", equipment="Raw"}
    frm6b = {name="FR-M6b", min=94.5, max=98.5, sex="F", equipment="Raw"}
    frm = {name="FR-M", min=39.5, max=999, sex="F", equipment="Raw"}
    frm1 = {name="FR-M1", min=39.5, max=48.5, sex="F", equipment="Raw"}
    frm2 = {name="FR-M2", min=49.5, max=58.5, sex="F", equipment="Raw"}
    frm3 = {name="FR-M3", min=59.5, max=68.5, sex="F", equipment="Raw"}
    frm4 = {name="FR-M4", min=69.5, max=78.5, sex="F", equipment="Raw"}
    frm5 = {name="FR-M5", min=79.5, max=88.5, sex="F", equipment="Raw"}
    frm6 = {name="FR-M6", min=89.5, max=98.5, sex="F", equipment="Raw"}
    frm7 = {name="FR-M7", min=99.5, max=999, sex="F", equipment="Raw"}
    frg = {name="FR-G", min=0, max=999, sex="F", equipment="Raw", place="G"}

    # Official divisions, Equipped Men.
    mo = {name="M-O", min=14, max=999, sex="M", equipment="Single-ply"}
    my = {name="M-Y", min=8, max=13, sex="M", equipment="Single-ply"}
    my1 = {name="M-Y1", min=8, max=9, sex="M", equipment="Single-ply"}
    my2 = {name="M-Y2", min=10, max=11, sex="M", equipment="Single-ply"}
    my3 = {name="M-Y3", min=12, max=13, sex="M", equipment="Single-ply"}
    mt = {name="M-T", min=14, max=19, sex="M", equipment="Single-ply"}
    mt1 = {name="M-T1", min=14, max=15, sex="M", equipment="Single-ply"}
    mt2 = {name="M-T2", min=16, max=17, sex="M", equipment="Single-ply"}
    mt3 = {name="M-T3", min=18, max=19, sex="M", equipment="Single-ply"}
    mtj = {name="M-TJ", min=14, max=23, sex="M", equipment="Single-ply"}
    msj = {name="M-SJ", min=14, max=18, sex="M", equipment="Single-ply"}
    mjr = {name="M-Jr", min=18, max=23, sex="M", equipment="Single-ply"}
    mm1a = {name="M-M1a", min=39.5, max=43.5, sex="M", equipment="Single-ply"}
    mm1b = {name="M-M1b", min=44.5, max=48.5, sex="M", equipment="Single-ply"}
    mm2a = {name="M-M2a", min=49.5, max=53.5, sex="M", equipment="Single-ply"}
    mm2b = {name="M-M2b", min=54.5, max=58.5, sex="M", equipment="Single-ply"}
    mm3a = {name="M-M3a", min=59.5, max=63.5, sex="M", equipment="Single-ply"}
    mm3b = {name="M-M3b", min=64.5, max=68.5, sex="M", equipment="Single-ply"}
    mm4a = {name="M-M4a", min=69.5, max=73.5, sex="M", equipment="Single-ply"}
    mm4b = {name="M-M4b", min=74.5, max=78.5, sex="M", equipment="Single-ply"}
    mm5a = {name="M-M5a", min=79.5, max=83.5, sex="M", equipment="Single-ply"}
    mm5b = {name="M-M5b", min=84.5, max=88.5, sex="M", equipment="Single-ply"}
    mm6a = {name="M-M6a", min=89.5, max=93.5, sex="M", equipment="Single-ply"}
    mm6b = {name="M-M6b", min=94.5, max=98.5, sex="M", equipment="Single-ply"}
    mm = {name="M-M", min=39.5, max=999, sex="M", equipment="Single-ply"}
    mm1 = {name="M-M1", min=39.5, max=48.5, sex="M", equipment="Single-ply"}
    mm2 = {name="M-M2", min=49.5, max=58.5, sex="M", equipment="Single-ply"}
    mm3 = {name="M-M3", min=59.5, max=68.5, sex="M", equipment="Single-ply"}
    mm4 = {name="M-M4", min=69.5, max=78.5, sex="M", equipment="Single-ply"}
    mm5 = {name="M-M5", min=79.5, max=88.5, sex="M", equipment="Single-ply"}
    mm6 = {name="M-M6", min=89.5, max=98.5, sex="M", equipment="Single-ply"}
    mm7 = {name="M-M7", min=99.5, max=999, sex="M", equipment="Single-ply"}
    mg = {name="M-G", min=0, max=999, sex="M", equipment="Single-ply", place="G"}

    # Official divisions, Equipped Women.
    fo = {name="F-O", min=14, max=999, sex="F", equipment="Single-ply"}
    fy = {name="F-Y", min=8, max=13, sex="F", equipment="Single-ply"}
    fy1 = {name="F-Y1", min=8, max=9, sex="F", equipment="Single-ply"}
    fy2 = {name="F-Y2", min=10, max=11, sex="F", equipment="Single-ply"}
    fy3 = {name="F-Y3", min=12, max=13, sex="F", equipment="Single-ply"}
    ft = {name="F-T", min=14, max=19, sex="F", equipment="Single-ply"}
    ft1 = {name="F-T1", min=14, max=15, sex="F", equipment="Single-ply"}
    ft2 = {name="F-T2", min=16, max=17, sex="F", equipment="Single-ply"}
    ft3 = {name="F-T3", min=18, max=19, sex="F", equipment="Single-ply"}
    ftj = {name="F-TJ", min=14, max=23, sex="F", equipment="Single-ply"}
    fsj = {name="F-SJ", min=14, max=18, sex="F", equipment="Single-ply"}
    fjr = {name="F-Jr", min=18, max=23, sex="F", equipment="Single-ply"}
    fm1a = {name="F-M1a", min=39.5, max=43.5, sex="F", equipment="Single-ply"}
    fm1b = {name="F-M1b", min=44.5, max=48.5, sex="F", equipment="Single-ply"}
    fm2a = {name="F-M2a", min=49.5, max=53.5, sex="F", equipment="Single-ply"}
    fm2b = {name="F-M2b", min=54.5, max=58.5, sex="F", equipment="Single-ply"}
    fm3a = {name="F-M3a", min=59.5, max=63.5, sex="F", equipment="Single-ply"}
    fm3b = {name="F-M3b", min=64.5, max=68.5, sex="F", equipment="Single-ply"}
    fm4a = {name="F-M4a", min=69.5, max=73.5, sex="F", equipment="Single-ply"}
    fm4b = {name="F-M4b", min=74.5, max=78.5, sex="F", equipment="Single-ply"}
    fm5a = {name="F-M5a", min=79.5, max=83.5, sex="F", equipment="Single-ply"}
    fm5b = {name="F-M5b", min=84.5, max=88.5, sex="F", equipment="Single-ply"}
    fm6a = {name="F-M6a", min=89.5, max=93.5, sex="F", equipment="Single-ply"}
    fm6b = {name="F-M6b", min=94.5, max=98.5, sex="F", equipment="Single-ply"}
    fm = {name="F-M", min=39.5, max=999, sex="F", equipment="Single-ply"}
    fm1 = {name="F-M1", min=39.5, max=48.5, sex="F", equipment="Single-ply"}
    fm2 = {name="F-M2", min=49.5, max=58.5, sex="F", equipment="Single-ply"}
    fm3 = {name="F-M3", min=59.5, max=68.5, sex="F", equipment="Single-ply"}
    fm4 = {name="F-M4", min=69.5, max=78.5, sex="F", equipment="Single-ply"}
    fm5 = {name="F-M5", min=79.5, max=88.5, sex="F", equipment="Single-ply"}
    fm6 = {name="F-M6", min=89.5, max=98.5, sex="F", equipment="Single-ply"}
    fm7 = {name="F-M7", min=99.5, max=999, sex="F", equipment="Single-ply"}
    fg = {name="F-G", min=0, max=999, sex="F", equipment="Single-ply", place="G"}

    # Junior Varsity.
    mrjv = {name="MR-JV", min=0, max=999, sex="M", equipment="Raw"}
    frjv = {name="FR-JV", min=0, max=999, sex="F", equipment="Raw"}
    mjv = {name="M-JV", min=0, max=999, sex="M", equipment="Single-ply"}
    fjv = {name="F-JV", min=0, max=999, sex="F", equipment="Single-ply"}

    # Varsity.
    mrv = {name="MR-V", min=0, max=999, sex="M", equipment="Raw"}
    frv = {name="FR-V", min=0, max=999, sex="F", equipment="Raw"}
    mv = {name="M-V", min=0, max=999, sex="M", equipment="Single-ply"}
    fv = {name="F-V", min=0, max=999, sex="F", equipment="Single-ply"}

    # High School.
    mrhs = {name="MR-HS", min=0, max=999, sex="M", equipment="Raw"}
    frhs = {name="FR-HS", min=0, max=999, sex="F", equipment="Raw"}
    mhs = {name="M-HS", min=0, max=999, sex="M", equipment="Single-ply"}
    fhs = {name="F-HS", min=0, max=999, sex="F", equipment="Single-ply"}

    # Collegiate.
    mrc = {name="MR-C", min=0, max=999, sex="M", equipment="Raw"}
    frc = {name="FR-C", min=0, max=999, sex="F", equipment="Raw"}
    mc = {name="M-C", min=0, max=999, sex="M", equipment="Single-ply"}
    fc = {name="F-C", min=0, max=999, sex="F", equipment="Single-ply"}

    # Military.
    mrmo = {name="MR-MO", min=0, max=999, sex="M", equipment="Raw"}
    frmo = {name="FR-MO", min=0, max=999, sex="F", equipment="Raw"}
    mmo = {name="M-MO", min=0, max=999, sex="M", equipment="Single-ply"}
    fmo = {name="F-MO", min=0, max=999, sex="F", equipment="Single-ply"}

    # Police and Fire.
    mrpf = {name="MR-PF", min=0, max=999, sex="M", equipment="Raw"}
    frpf = {name="FR-PF", min=0, max=999, sex="F", equipment="Raw"}
    mpf = {name="M-PF", min=0, max=999, sex="M", equipment="Single-ply"}
    fpf = {name="F-PF", min=0, max=999, sex="F", equipment="Single-ply"}

    # Police, Fire, and Military.
    mrpfm = {name="MR-PFM", min=0, max=999, sex="M", equipment="Raw"}
    frpfm = {name="FR-PFM", min=0, max=999, sex="F", equipment="Raw"}
    mpfm = {name="M-PFM", min=0, max=999, sex="M", equipment="Single-ply"}
    fpfm = {name="F-PFM", min=0, max=999, sex="F", equipment="Single-ply"}

    # Special Olympics.
    mrso = {name="MR-SO", min=0, max=999, sex="M", equipment="Raw"}
    frso = {name="FR-SO", min=0, max=999, sex="F", equipment="Raw"}
    mso = {name="M-SO", min=0, max=999, sex="M", equipment="Single-ply"}
    fso = {name="F-SO", min=0, max=999, sex="F", equipment="Single-ply"}

[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["2015-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["47","52","57","63","69","76","84","84+"]
    date_range=["2021-01-01","9999-01-01"]
    sex = "F"

[weightclasses.year2020_F]
    classes = ["47","52","57","63","72","84","84+"]
    date_range=["2015-01-01","2020-12-31"]
    sex = "F"


[weightclasses.junior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2015-01-01","9999-01-01"]
    sex = "M"
    divisions = [
        "MR-T", "MR-T1", "MR-T2", "MR-T3", "MR-TJ", "MR-Jr", "MR-SJ",
        "M-T", "M-T1", "M-T2", "M-T3", "M-TJ", "M-Jr",
	"MR-JV", "M-JV", "MR-V", "M-V", "MR-HS", "M-HS", "MR-C", "M-C"
    ]

[weightclasses.junior_F]
    classes = ["43","47","52","57","63","72","84","84+"]
    date_range=["2015-01-01","9999-01-01"]
    sex = "F"
    divisions = [
        "FR-T", "FR-T1", "FR-T2", "FR-T3", "FR-TJ", "FR-Jr",
        "F-T", "F-T1", "F-T2", "F-T3", "F-TJ", "F-Jr",
	"FR-JV", "F-JV", "FR-V", "F-V", "FR-HS", "F-HS", "FR-C", "F-C"
    ]

[weightclasses.youth_M]
    classes = ["30","35","40","44","48","53","59","66","74","83","93","105","120","120+"]
    date_range=["2015-01-01","9999-01-01"]
    sex = "M"
    divisions = ["MR-Y", "MR-Y1", "MR-Y2", "MR-Y3", "M-Y", "M-Y1", "M-Y2", "M-Y3"]

[weightclasses.youth_F]
    classes = ["30","35","40","43","47","52","57","63","72","84","84+"]
    date_range=["2015-01-01","9999-01-01"]
    sex = "F"
    divisions = ["FR-Y", "FR-Y1", "FR-Y2", "FR-Y3", "F-Y", "F-Y1", "F-Y2", "F-Y3"]

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["0000-01-01","2014-12-31"]
    sex = "M"

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2014-12-31"]
    sex = "F"

[exemptions]
	2001 = ["ExemptWeightClassConsistency"] # No female weightclasses.
	2201 = ["ExemptDivision"] # Apparent sub-juniors in the juniors category.
	2401 = ["ExemptDivision"] # Apparent sub-juniors in the juniors category.
    2303 = ["ExemptWeightClassConsistency"]  # no weightclasses
