[divisions]
    # The main division used for almost everything.
    girls = {name="Girls", min=13, max=19, sex="F"}

    freshmen = {name="Freshmen", min=13, max=15, sex="F"}
    jv = {name="Junior Varsity", min=0, max=999, sex="F"}
    v = {name="Varsity", min=0, max=999, sex="F"}

    # Divisions (within a region of Texas).
    div1 = {name="Div 1", min=0, max=999, sex="F"}
    div2 = {name="Div 2", min=0, max=999, sex="F"}
    div3 = {name="Div 3", min=0, max=999, sex="F"}

	# Regions (I'm pretty sure these are errors).
    reg4 = {name="Region 4", min=0, max=999, sex="F"}

    # Sometimes boys are listed in THSWPA for some reason...
    boys = {name="Boys", min=13, max=19, sex="M"}


# THSWPA uses pounds classes with exact pound values.
#
# Although the classes appear as "181", "198" etc., the rulebook specifies that the
# precise maximum value allowed in that class is "181.5", "198.5", and so on for each.

[weightclasses.default_F]
    classes = ["44.23","47.85","51.94","56.02","60.1","67.36","75.07","82.33","90.04","100.02","110","110+"]
    date_range=["2024-01-01","9999-01-01"]
    sex = "F"

[weightclasses.default_M]
    classes = ["51.71","55.79","59.87","67.13","74.84","82.1","89.81","99.79","109.77","124.74","124.74+"]
    date_range=["0000-01-01","9999-01-01"]
    sex = "M"

[weightclasses.old_F]
    classes = ["44.23","47.85","51.94","56.02","60.1","67.36","75.07","82.33","90.04","100.02","117.71","100.02+","117.71+"]
    date_range=["0000-01-01","2023-12-31"]
    sex = "F"

[exemptions]
