# Configuration for unsanctioned USA meets.
[options]
    require_manual_disambiguation = true

[divisions]
    # An empty divisions table disables configuration for USA-UA.

[weightclasses.traditional_M]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1900-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.traditional_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["1900-01-01", "9999-01-01"]
    sex = "F"

[exemptions]
    1902 = ["ExemptWeightClassConsistency"] # Uses very weird weightclasses.
