[divisions]
# Intentionally left blank.

[weightclasses]
# Intentionally left blank.

[exemptions]
    2502 = ["ExemptWeightClassConsistency"]
    2503 = ["ExemptWeightClassConsistency"] # placed by total I think