[package]
name = "goodlift-import"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
color-eyre = "0.6"
csv = "1.3"
pico-args = "0.5"
serde = { workspace = true, features = ["derive"] }
ureq = "2.10"
