[divisions]
    open = {name ="Open",min=0,max=999}
    masters40_44 = {name="Masters 40-44", min=40, max=45}
    masters45_49 = {name="Masters 45-49", min=45, max=49}
    masters50_54 = {name="Masters 50-54", min=50, max=54}
    masters55_59 = {name="Masters 55-59", min=55, max=59}
    masters60_64 = {name="Masters 60-64", min=60, max=64}
    masters65_69 = {name="Masters 65-69", min=65, max=69}
    masters70_74 = {name="Masters 70-74", min=70, max=74}
    masters75_79 = {name="Masters 75-79", min=75, max=79}

    youth = {name="Youth", min=5, max=14}
    teen13_15 = {name="Teen 13-15", min=13, max=15}
    teen16_17 = {name="Teen 16-17", min=16, max=17}
    teen15_19 = {name="Teen 15-19", min=15, max=19}
    teen13_19 = {name="Sub-Juniors", min=13, max=19}
    juniors20_23 = {name="Juniors", min=20, max=23}

    disabled = {name ="Disabled",min=0,max=999}

[weightclasses.M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","110+","140+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "M"

[weightclasses.F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]
    2401 = ["ExemptWeightClassConsistency","ExemptDivision"] # no classes or divisions
