[divisions]
    open = {name = "Open", min = 0, max = 999}
    youth = {name = "Youth", min = 0, max = 12} #Not an official division
    t_13_15 = {name = "T 13-15", min = 13, max = 15}
    t_16_17 = {name = "T 16-17", min = 16, max = 17}
    t_18_19 = {name = "T 18-19", min = 18, max = 19}
    teenage = {name = "Teenage", min = 13, max = 19}
    juniors = {name = "Junior", min = 20, max = 23}
    submasters = {name = "Submasters", min = 35, max = 39}
    m_40_44 = {name = "Masters 40-44", min = 40, max = 44}
    m_45_49 = {name = "Masters 45-49", min = 45, max = 49}
    m_50_54 = {name = "Masters 50-54", min = 50, max = 54}
    m_55_59 = {name = "Masters 55-59", min = 55, max = 59}
    m_60_64 = {name = "Masters 60-64", min = 60, max = 64}
    m_65_69 = {name = "Masters 65-69", min = 65, max = 69}
    m_70_74 = {name = "Masters 70-74", min = 70, max = 74}
    m_75_79 = {name = "Masters 75-79", min = 75, max = 79}
    m_80p = {name = "Masters 80+", min = 80, max = 999}
    guest = {name = "Guest", min = 0, max = 999}

[weightclasses.default_M]
    classes = ["56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "F"

[exemptions]
    2101 = ["ExemptDivision", "ExemptWeightClassConsistency"] # Janky divisions
    2201 = ["ExemptDivision", "ExemptWeightClassConsistency"] # Janky divisions
    2202 = ["ExemptDivision", "ExemptWeightClassConsistency"] # Janky divisions
    2301 = ["ExemptWeightClassConsistency"] # Janky weight classes
    2401 = ["ExemptWeightClassConsistency"] # Janky weight classes