[divisions]
    1A2A = {name="1A-2A", min=13, max=19}
    3A = {name="3A", min=13, max=19}
    4A = {name="4A", min=13, max=19}
    5A = {name="5A", min=13, max=19}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range=["0000-01-01","9999-01-01"]
    sex = "M"
[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range=["0000-01-01","9999-01-01"]
    sex = "F"
[exemptions]
