[divisions]
    aktive = {name ="Aktive",min=0,max=999,equipment="Raw"}
    jugend = {name = "Jugend",min=0,max=18,equipment="Raw"}
    junioren = {name = "Junioren",min=0,max=23,equipment="Raw"}
    teen = {name = "Teen",min=0,max=18,equipment="Raw"}
    mastersi = {name = "Masters I",min=40,max=49,equipment="Raw"}
    mastersii = {name = "Masters II",min=50,max=59,equipment="Raw"}
    mastersiii = {name = "Masters III",min=60,max=69,equipment="Raw"}
    mastersiv = {name = "Masters IV",min=70,max=999,equipment="Raw"}

[weightclasses.default_M]
    classes = ["75","95","115","115+"]
    date_range = ["0000-01-01", "9999-01-01"]
    sex = "M"

[exemptions]
    0701 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    0702 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    0703 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    0704 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    0801 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    0802 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    0803 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    0804 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    0805 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    0806 = ["ExemptWeightClassConsistency"]  # Bench didn't use weightclasses.
    0807 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    0903 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    0905 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    0909 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    0901 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1001 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1002 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1003 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1004 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1005 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1006 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1007 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1008 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    0908 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1101 = ["ExemptWeightClassConsistency"]  # No BW or weightclasses.
    1102 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    1104 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    1105 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    1106 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    1107 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    1108 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    1109 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    1110 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    1111 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    1112 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    1113 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    1103 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1201 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    1202 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1401 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1203 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
