[options]
    require_manual_disambiguation = true

[divisions]
    open = {name = "Open", min=0, max=999}
    juniors = {name = "Juniors", min=20, max=23}
    masters = {name = "Masters", min=40, max=999}

    o = {name = "O", min=0, max=999}
    y = {name = "Y", min=0, max=12}
    t1 = {name = "T1", min=13, max=15}
    t2 = {name = "T2", min=16, max=17}
    t3 = {name = "T3", min=18, max=19}
    j = {name = "J", min=20, max=23}
    m1 = {name = "M1", min=40, max=44}
    m2 = {name = "M2", min=45, max=49}
    m3 = {name = "M3", min=50, max=54}
    m4 = {name = "M4", min=55, max=59}
    m5 = {name = "M5", min=60, max=64}
    m6 = {name = "M6", min=65, max=69}
    m7 = {name = "M7", min=70, max=74}
    m8 = {name = "M8", min=75, max=79}
    m9 = {name = "M9", min=80, max=999}
    teen = {name = "T", min=13, max=19}

[weightclasses.M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["0000-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","110","110+"]
    date_range = ["0000-01-01", "9999-01-01"]
    sex = "F"

[exemptions]
    2301 = ["ExemptDivision"]
