[package]
name = "usernames"
version = "0.1.0"
authors = ["Matt Pearce <matt@openpowerlifting.org>"]
description = """
For converting a name into the corresponding username.
"""
license = "AGPL-3.0-or-later"
edition = "2018"

[dependencies]
