# Exempts lifters from consistency checks.

[sex]
usernames = [
	"ardelthomas",
	"jaxsonwearing",
	"alexandrawatt",
	"angelflores1",
	"adamhenson2",
	"carolinewright",
	"oscarhood",
	"michaelnguyen",
	"taylorselman"
]

[bodyweight]
usernames = [
]
