# Exempts lifters from consistency checks.

[sex]
usernames = [
	"ardelthomas",
	"jaxsonwearing",
	"alexandrawatt",
	"angelflores1",
	"adamhenson2",
	"carolinewright",
	"catherinehamric",
	"oscarhood",
	"michaelnguyen",
	"taylorselman",
	"harmoniegivens",
	"peejvoudiotis",
        "nessfry",
        "lucasrojas",
	"peytonsmith4"
]

[bodyweight]
usernames = [
]
