# Configuration for WPC-Poland.

[divisions]
    open = {name="Open", min=0, max=999}
    s24_32 = {name="Seniors 24-32", min=24, max=32}
    sm33_39 = {name="Submasters 33-39", min=33, max=39}
    t13_15 = {name="Teen 13-15", min=13, max=15}
    t16_17 = {name="Teen 16-17", min=16, max=17}
    t18_19 = {name="Teen 18-19", min=18, max=19}
    juniors = {name="Juniors 20-23", min=20, max=23}
    m40_44 = {name="Masters 40-44", min=40, max=44} # M1
    m45_49 = {name="Masters 45-49", min=45, max=49} # M2
    m50_54 = {name="Masters 50-54", min=50, max=54} # M3
    m55_59 = {name="Masters 55-59", min=55, max=59} # M4
    m60_64 = {name="Masters 60-64", min=60, max=64} # M5
    m65_69 = {name="Masters 65-69", min=65, max=69} # M6
    m70_74 = {name="Masters 70-74", min=70, max=74} # M7
    m75_79 = {name="Masters 75-79", min=75, max=79} # M8
    
    t16_19 = {name="Teen 16-19", min=16, max=19}
    MPF = {name="MPF", min=0, max=999} #Police/Fire

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]
    1901 = ["ExemptWeightClassConsistency"] #Made up the SHW classes as they went along
    2001 = ["ExemptWeightClassConsistency", "ExemptDivision"] #Divisions and weightclasses are all over the show
    2101 = ["ExemptWeightClassConsistency", "ExemptDivision"] #Divisions and weightclasses are all over the show
    2102 = ["ExemptWeightClassConsistency", "ExemptDivision"] #Divisions and weightclasses are all over the show
    2103 = ["ExemptWeightClassConsistency", "ExemptDivision"] #Divisions and weightclasses are all over the show