[divisions]
    open = {name = "O", min = 0, max = 999}
    # pre-IPF
    teen_13_15 = {name = "T1", min = 13, max = 15}
    teen_16_17 = {name = "T2", min = 16, max = 17}
    teen_18_19 = {name = "T3", min = 18, max = 19}
    juniors_20_23 = {name = "J", min = 20, max = 23}
    masters_40_44 = {name = "M1", min = 40, max = 44}
    masters_45_49 = {name = "M2", min = 45, max = 49}
    masters_50_54 = {name = "M3", min = 50, max = 54}
    masters_55_59 = {name = "M4", min = 55, max = 59}
    masters_60_64 = {name = "M5", min = 60, max = 64}
    masters_65_69 = {name = "M6", min = 64, max = 69}
    masters_70_74 = {name = "M7", min = 70, max = 74}
    teen = {name = "T", min = 13, max = 19}

    # different meets use different teen division definitions
    teen_13_16 = {name = "Teens1", min = 13, max = 16}
    teen_17_19 = {name = "Teens2", min = 17, max = 19}

    # IPF
    master1 = {name="Masters 1",min=39.5,max=48.5}
    master2 = {name="Masters 2",min=49.5,max=58.5}
    master3 = {name="Masters 3",min=59.5,max=68.5}
    master4 = {name="Masters 4",min=69.5,max=999}
    subjunior = {name="Sub-Juniors", min=0, max=17.5}
    junior = {name="Juniors", min=18, max=23}

    guest = {name = "G", min = 0, max = 999}
    para = {name = "Paralympic", min = 0, max = 999}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1990-01-01", "2023-12-31"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["1990-01-01", "2023-12-31"]
    sex = "F"

[weightclasses.IPF_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range = ["2024-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.IPF_F]
    classes = ["47","52","57","63","69","76","84","84+"]
    date_range = ["2024-01-01", "9999-01-01"]
    sex = "F"

[weightclasses.junior_F]
    classes = ["43","47","52","57","63","69","76","84","84+"]
    date_range=["2024-01-01","9999-01-01"]
    sex = "F"
    divisions = ["Juniors","Sub-Juniors"]

[exemptions]
