# Configuration for 100% RAW.

[options]
    require_manual_disambiguation = true

[divisions]
	# Youth divisions, only used historically.
	youth_5 = {name="Youth 5 & Under", min=0, max=5, equipment="Raw"}
	youth_6_7 = {name="Youth 6-7", min=6, max=7, equipment="Raw"}
	youth_8_9 = {name="Youth 8-9", min=8, max=9, equipment="Raw"}
	youth_10_11 = {name="Youth 10-11", min=10, max=11, equipment="Raw"}
	youth_11 = {name="Youth 11 & Under", min=0, max=11, equipment="Raw"}

    # Age in 100% RAW is determined by exact age on date of meet.
    open = {name = "Open", min = 0, max = 999, equipment="Raw"}
    youth = {name = "Youth", min = 0, max = 11, equipment="Raw"}
    teen_12 = {name = "Teen 12-13", min = 12, max = 13, equipment="Raw"}
    teen_14 = {name = "Teen 14-15", min = 14, max = 15, equipment="Raw"}
    teen_16 = {name = "Teen 16-17", min = 16, max = 17, equipment="Raw"}
    teen_18 = {name = "Teen 18-19", min = 18, max = 19, equipment="Raw"}
    junior = {name = "Juniors 20-24", min = 20, max = 24, equipment="Raw"}
    submaster = {name = "Submasters 35-39", min = 35, max = 39, equipment="Raw"}
    master_40 = {name = "Masters 40-44", min = 40, max = 44, equipment="Raw"}
    master_45 = {name = "Masters 45-49", min = 45, max = 49, equipment="Raw"}
    master_50 = {name = "Masters 50-54", min = 50, max = 54, equipment="Raw"}
    master_55 = {name = "Masters 55-59", min = 55, max = 59, equipment="Raw"}
    master_60 = {name = "Masters 60-64", min = 60, max = 64, equipment="Raw"}
    master_65 = {name = "Masters 65-69", min = 65, max = 69, equipment="Raw"}
    master_70 = {name = "Masters 70-74", min = 70, max = 74, equipment="Raw"}
    master_75 = {name = "Masters 75-79", min = 75, max = 79, equipment="Raw"}
    master_80 = {name = "Masters 80+", min = 80, max = 999, equipment="Raw"}
    master_90 = {name = "Masters 90+", min = 90, max = 999, equipment="Raw"}
    lfm = {name = "Law/Fire/Military", min = 0, max = 999, equipment="Raw"}
    special = {name = "Special Olympics", min = 0, max = 999, equipment="Raw"}
    handicapped = {name = "Handicapped", min = 0, max = 999, equipment="Raw"}

    # "Classic" divisions, which permit the use of knee sleeves.
    # This conflates equipment with division, but we don't track bare knees records.
    c_open = {name = "Classic Open", min = 0, max = 999, equipment="Raw"}
    c_youth = {name = "Classic Youth", min = 0, max = 11, equipment="Raw"}
    c_teen_12 = {name = "Classic Teen 12-13", min = 12, max = 13, equipment="Raw"}
    c_teen_14 = {name = "Classic Teen 14-15", min = 14, max = 15, equipment="Raw"}
    c_teen_16 = {name = "Classic Teen 16-17", min = 16, max = 17, equipment="Raw"}
    c_teen_18 = {name = "Classic Teen 18-19", min = 18, max = 19, equipment="Raw"}
    c_junior = {name = "Classic Juniors 20-24", min = 20, max = 24, equipment="Raw"}
    c_submaster = {name = "Classic Submasters 35-39", min = 35, max = 39, equipment="Raw"}
    c_master_40 = {name = "Classic Masters 40-44", min = 40, max = 44, equipment="Raw"}
    c_master_45 = {name = "Classic Masters 45-49", min = 45, max = 49, equipment="Raw"}
    c_master_50 = {name = "Classic Masters 50-54", min = 50, max = 54, equipment="Raw"}
    c_master_55 = {name = "Classic Masters 55-59", min = 55, max = 59, equipment="Raw"}
    c_master_60 = {name = "Classic Masters 60-64", min = 60, max = 64, equipment="Raw"}
    c_master_65 = {name = "Classic Masters 65-69", min = 65, max = 69, equipment="Raw"}
    c_master_70 = {name = "Classic Masters 70-74", min = 70, max = 74, equipment="Raw"}
    c_master_75 = {name = "Classic Masters 75-79", min = 75, max = 79, equipment="Raw"}
    c_master_80 = {name = "Classic Masters 80+", min = 80, max = 999, equipment="Raw"}
    c_lfm = {name = "Classic Law/Fire/Military", min = 0, max = 999, equipment="Raw"}
    c_special = {name = "Classic Special Olympics", min = 0, max = 999, equipment="Raw"}
    c_handicapped = {name = "Classic Handicapped", min = 0, max = 999, equipment="Raw"}

    # Special occurrences.
    highschool_froshsoph = {name = "Frosh/Soph", min = 14, max = 17, equipment="Raw"}
    highschool_juniorsenior = {name = "Junior/Senior", min = 16, max = 19, equipment="Raw"}
	seniors_20_24 = {name = "Seniors 20-24", min=20, max=24, equipment="Raw"}
    seniors_25_29 = {name = "Seniors 25-29", min=25, max=29, equipment="Raw"}
	seniors_30_34 = {name = "Seniors 30-34", min=30, max=34, equipment="Raw"}

[weightclasses.current_M]
    classes = ["48","52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["2013-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.current_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["2013-01-01", "9999-01-01"]
    sex = "F"


# From https://web.archive.org/web/20100331160114/http://www.rawpowerlifting.com:80/pdf/GeneralRules.pdf
# End date is a guess -- the 2015 classes are same as the 2018 classes, though.
[weightclasses.old_M]
    classes = ["30","35","40","44.5","48","52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["2005-01-01", "2013-01-01"]
    sex = "M"

#They had a 145 class at some point, no idea when it was removed.
[weightclasses.old_M2]
    classes = ["30","35","40","44.5","48","52","56","60","67.5","75","82.5","90","100","110","125","145","145+"]
    date_range = ["1990-01-01", "2004-12-31"]
    sex = "M"

[weightclasses.old_F]
    classes = ["30","35","40","44.5","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["1999-01-01", "2013-01-01"]
    sex = "F"

[exemptions]
    0503 = ["ExemptWeightClassConsistency"]  # Used 145
    0802 = ["ExemptWeightClassConsistency"]  # Used a different SHW class.
    0803 = ["ExemptWeightClassConsistency"]  # No 44.5 class
    1203 = ["ExemptAge","ExemptWeightClassConsistency"] # Lifter of age 4, 44 used for youth.
    1207 = ["ExemptWeightClassConsistency"]  # No 44.5 class
    1501 = ["ExemptWeightClassConsistency"]  # Used old classes for youth.
    1503 = ["ExemptWeightClassConsistency"]  # Used old classes for youth.
    1605 = ["ExemptWeightClassConsistency"]  # Used old classes for youth.
    1615 = ["ExemptWeightClassConsistency"]  # Used old classes for youth.
    1826 = ["ExemptWeightClassConsistency"]  # Used old classes for youth.
    1829 = ["ExemptWeightClassConsistency"]  # Used old classes for youth.
    1833 = ["ExemptWeightClassConsistency"]  # Used old classes for youth.
    1906 = ["ExemptWeightClassConsistency"]  # Used old classes for youth.
    1925 = ["ExemptWeightClassConsistency"]  # Used new classes for youth (30kg).
    2003 = ["ExemptWeightClassConsistency"]  # Used new classes for youth (30kg).
    2008 = ["ExemptWeightClassConsistency"]  # Used new classes for youth (30kg).
    2014 = ["ExemptWeightClassConsistency"]  # Used new classes for youth (30kg).
