# Configuration for PZKFiTS.

[divisions]
    open_f = {name = "Seniorki",min=0,max=999,sex='F'}
    juniors16_f = {name = "Juniorki do lat 16",min=0,max=15.5,sex='F'}
    juniors18_f = {name = "Juniorki do lat 18",min=0,max=27.5,sex='F'}
    juniors20_f = {name = "Juniorki do lat 20",min=0,max=19.5,sex='F'}
    juniors23_f = {name = "Juniorki do lat 23",min=0,max=22.5,sex='F'}
    masters4049_f = {name = "Weteranki 40-49 lat",min=39.5,max=48.5,sex='F'}
    masters5059_f = {name = "Weteranki 50-59 lat",min=49.5,max=58.5,sex='F'}
    masters6069_f = {name = "Weteranki 60-69 lat",min=59.5,max=68.5,sex='F'}
    masters70p_f = {name = "Weteranki +70 lat",min=69.5,max=999,sex='F'}

    masters40p_f = {name = "Weteranki +40 lat",min=39.5,max=999,sex='F'}
    masters50p_f = {name = "Weteranki +50 lat",min=49.5,max=999,sex='F'}
    masters_f = {name = "Weteranki",min=39.5,max=999,sex='F'}

    open_m = {name = "Seniorzy",min=0,max=999,sex='M'}
    juniors16_m = {name = "Juniorzy do lat 16",min=0,max=15.5,sex='M'}
    juniors18_m = {name = "Juniorzy do lat 18",min=0,max=27.5,sex='M'}
    juniors20_m = {name = "Juniorzy do lat 20",min=0,max=19.5,sex='M'}
    juniors23_m = {name = "Juniorzy do lat 23",min=0,max=22.5,sex='M'}
    masters4049_m = {name = "Weterani 40-49 lat",min=39.5,max=48.5,sex='M'}
    masters5059_m = {name = "Weterani 50-59 lat",min=49.5,max=58.5,sex='M'}
    masters6069_m = {name = "Weterani 60-69 lat",min=59.5,max=68.5,sex='M'}
    masters70p_m = {name = "Weterani +70 lat",min=69.5,max=999,sex='M'}

    masters40p_m = {name = "Weterani +40 lat",min=39.5,max=999,sex='M'}
    masters50p_m = {name = "Weterani +50 lat",min=49.5,max=999,sex='M'}
    masters = {name = "Weterani",min=39.5,max=999}
[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["47","52","57","63","69","76","84","84+"]
    date_range=["2021-01-01","9999-01-01"]
    sex = "F"

[weightclasses.year2020_F]
    classes = ["47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","2020-12-31"]
    sex = "F"

[weightclasses.junior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["Juniorzy do lat 23","Juniorzy do lat 20","Juniorzy do lat 18","Juniorzy do lat 16"]

[weightclasses.junior_F]
    classes = ["43","47","52","57","63","69","76","84","84+"]
    date_range=["2021-01-01","9999-01-01"]
    sex = "F"
    divisions = ["Juniorki do lat 23","Juniorki do lat 20","Juniorki do lat 18","Juniorki do lat 16"]

[weightclasses.year2020_junior_F]
    classes = ["43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","2020-12-31"]
    sex = "F"
    divisions = ["Juniorki do lat 23","Juniorki do lat 20","Juniorki do lat 18","Juniorki do lat 16"]

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"

[exemptions]
    1001 = ["ExemptWeightClassConsistency"]  # 44Kg women in 48
    1202 = ["ExemptWeightClassConsistency"]  # No weightclasses for Masters
    1401 = ["ExemptWeightClassConsistency"]  # Different weightclasses for Masters
    1403 = ["ExemptWeightClassConsistency"]  # Different weightclasses for Masters
    1404 = ["ExemptWeightClassConsistency"]  # Different weightclasses for Juniors
    1501 = ["ExemptWeightClassConsistency"]  # Uses 93+.
    1503 = ["ExemptWeightClassConsistency"]  # No weightclasses for Juniors
    1502 = ["ExemptWeightClassConsistency"]  # No weightclasses for Masters
    1504 = ["ExemptWeightClassConsistency"]  # No weightclasses for Juniors
    1506 = ["ExemptWeightClassConsistency"]  # No weightclasses for Masters
    1508 = ["ExemptWeightClassConsistency"]  # No weightclasses for Juniors
    1601 = ["ExemptWeightClassConsistency"]  # No weightclasses for Juniors
    1602 = ["ExemptWeightClassConsistency"]  # No weightclasses for Masters
    1604 = ["ExemptWeightClassConsistency"]  # No weightclasses for Masters or Juniors     
    1702 = ["ExemptWeightClassConsistency"]  # No weightclasses for Juniors
    1703 = ["ExemptWeightClassConsistency"]  # Reduced weightclasses for Jrs & Masters
    1704 = ["ExemptWeightClassConsistency"]  # Reduced weightclasses for Jrs & Masters
    1705 = ["ExemptWeightClassConsistency"]  # Reduced weightclasses for Jrs & Masters
    1801 = ["ExemptWeightClassConsistency"]  # Reduced weightclasses for Jrs & Masters
    1901 = ["ExemptWeightClassConsistency"]  # Lowest Juniors class was -52kg.
    1902 = ["ExemptWeightClassConsistency"]  # Reduced weightclasses for Jrs
    1903 = ["ExemptWeightClassConsistency"]  # Reduced weightclasses for Jrs & Masters
    2102 = ["ExemptWeightClassConsistency"]  # Reduced weightclasses for Jrs & Masters
    2201 = ["ExemptWeightClassConsistency"]  # Reduced weightclasses for Jrs & Masters
    2202 = ["ExemptWeightClassConsistency"]  # No 47kg womens
    2204 = ["ExemptWeightClassConsistency"]  # Reduced weightclasses
    2304 = ["ExemptWeightClassConsistency"]  # Reduced weightclasses for Jrs & Masters
    2305 = ["ExemptWeightClassConsistency"]  # Reduced weightclasses for Jrs & Masters
    2307 = ["ExemptWeightClassConsistency"]  # Reduced weightclasses
    2308 = ["ExemptWeightClassConsistency"]  # Reduced weightclasses
    2309 = ["ExemptWeightClassConsistency"]  # No 47kg womens or 66kg men
    2401 = ["ExemptWeightClassConsistency"]  # Reduced weightclasses for Jrs & Masters
    2402 = ["ExemptWeightClassConsistency"]  # Reduced weightclasses for Jrs & Masters
    2406 = ["ExemptWeightClassConsistency"]  # Reduced weightclasses
