# Configuration for RPS.

[options]
	require_manual_disambiguation = true

# Divisions are specified here: https://www.revolutionpowerlifting.com/rules/?page_id=10
[divisions]
    # Open divisions.
    ama_open = {name = "Amateur Open", min = 0, max = 999, tested="Yes"}
    pro_open = {name = "Pro Open", min = 0, max = 999}

    # Elite divisions. Elite only has an "Open" category, no age categories.
    # Nevertheless, some meets include a Juniors division erroneously.
    #
    # Confusingly, the Elite division counts in competition as the Pro division.
    # It's just a way to say "Tested Pro" and isn't actually a separate division.
    # Nevertheless for purposes of records it is a division.
    elite_open = {name = "Elite Open", min = 0, max = 999, tested="Yes"}
    elite_teen_18_19 = {name = "Elite Teen 18-19", min = 18, max = 19, tested="Yes"}
    elite_junior_20_23 = {name = "Elite Juniors 20-23", min = 20, max = 23, tested="Yes"}
    elite_submaster_33_39 = {name = "Elite Submasters 33-39", min = 33, max = 39, tested="Yes"}

    # Youth -- Amateur only.
    ama_youth = {name = "Amateur Youth", min = 5, max = 13, tested="Yes"}
    ama_youth_8 = {name = "Amateur Youth 8", min = 8, max = 8, tested="Yes"}
    ama_youth_9 = {name = "Amateur Youth 9", min = 9, max = 9, tested="Yes"}
    ama_youth_10 = {name = "Amateur Youth 10", min = 10, max = 10, tested="Yes"}
    ama_youth_11 = {name = "Amateur Youth 11", min = 11, max = 11, tested="Yes"}
    ama_youth_12 = {name = "Amateur Youth 12", min = 12, max = 12, tested="Yes"}

    # Teens -- Amateur only.
    ama_teen_14_15 = {name = "Amateur Teen 14-15", min = 14, max = 15, tested="Yes"}
    ama_teen_16_17 = {name = "Amateur Teen 16-17", min = 16, max = 17, tested="Yes"}
    ama_teen_18_19 = {name = "Amateur Teen 18-19", min = 18, max = 19, tested="Yes"}

    # Pro Teen, not official divisions but have been used in several meets
    pro_teen_14_15 = {name = "Pro Teen 14-15", min = 14, max = 15}
    pro_teen_16_17 = {name = "Pro Teen 16-17", min = 16, max = 17}
    pro_teen_18_19 = {name = "Pro Teen 18-19", min = 18, max = 19}
    
    # Juniors.
    ama_junior_20_23 = {name = "Amateur Juniors 20-23", min = 20, max = 23, tested="Yes"}
    pro_junior_20_23 = {name = "Pro Juniors 20-23", min = 20, max = 23}

    # Submasters.
    ama_submaster_33_39 = {name = "Amateur Submasters 33-39", min = 33, max = 39, tested="Yes"}
    pro_submaster_33_39 = {name = "Pro Submasters 33-39", min = 33, max = 39}

    # Amateur Masters.
    ama_master_40_44 = {name = "Amateur Masters 40-44", min = 40, max = 44, tested="Yes"}
    ama_master_45_49 = {name = "Amateur Masters 45-49", min = 45, max = 49, tested="Yes"}
    ama_master_50_54 = {name = "Amateur Masters 50-54", min = 50, max = 54, tested="Yes"}
    ama_master_55_59 = {name = "Amateur Masters 55-59", min = 55, max = 59, tested="Yes"}
    ama_master_60_64 = {name = "Amateur Masters 60-64", min = 60, max = 64, tested="Yes"}
    ama_master_65_69 = {name = "Amateur Masters 65-69", min = 65, max = 69, tested="Yes"}
    ama_master_70_74 = {name = "Amateur Masters 70-74", min = 70, max = 74, tested="Yes"}
    ama_master_75_79 = {name = "Amateur Masters 75-79", min = 75, max = 79, tested="Yes"}
    ama_master_80_84 = {name = "Amateur Masters 80-84", min = 80, max = 84, tested="Yes"}
    ama_master_85_89 = {name = "Amateur Masters 85-89", min = 85, max = 89, tested="Yes"}
    ama_master_90_94 = {name = "Amateur Masters 90-94", min = 90, max = 94, tested="Yes"}
    ama_master_95_99 = {name = "Amateur Masters 95-99", min = 95, max = 99, tested="Yes"}
    ama_master_100p  = {name = "Amateur Masters 100+", min = 100, max = 999, tested="Yes"}

    # Pro Masters.
    pro_master_40_44 = {name = "Pro Masters 40-44", min = 40, max = 44}
    pro_master_45_49 = {name = "Pro Masters 45-49", min = 45, max = 49}
    pro_master_50_54 = {name = "Pro Masters 50-54", min = 50, max = 54}
    pro_master_55_59 = {name = "Pro Masters 55-59", min = 55, max = 59}
    pro_master_60_64 = {name = "Pro Masters 60-64", min = 60, max = 64}
    pro_master_65_69 = {name = "Pro Masters 65-69", min = 65, max = 69}
    pro_master_70_74 = {name = "Pro Masters 70-74", min = 70, max = 74}
    pro_master_75_79 = {name = "Pro Masters 75-79", min = 75, max = 79}
    pro_master_80_84 = {name = "Pro Masters 80-84", min = 80, max = 84}
    pro_master_85_89 = {name = "Pro Masters 85-89", min = 85, max = 89}
    pro_master_90_94 = {name = "Pro Masters 90-94", min = 90, max = 94}
    pro_master_95_99 = {name = "Pro Masters 95-99", min = 95, max = 99}
    pro_master_100p  = {name = "Pro Masters 100+", min = 100, max = 999}

    # Less specific divisions that have been used in meets
    pro_master = {name = "Pro Masters", min = 40, max = 999}
    pro_master_50 = {name = "Pro Masters 50+", min = 50, max = 999}
    ama_master = {name = "Amateur Masters", min = 40, max = 999, tested="Yes"}
    ama_master_50 = {name = "Amateur Masters 50+", min = 50, max = 999, tested="Yes"}
    ama_teen = {name = "Amateur Teen", min = 14, max = 19, tested="Yes"}
    ama_teen_13_15 = {name = "Amateur Teen 13-15", min = 13, max = 15, tested="Yes"}


    # Occupation-based divisions, limited to only Open and Master 50+.
    # Except some meet directors ignore that and use all the Masters divisions.
    ama_police_open = {name = "Police Amateur Open", min = 0, max = 999, tested="Yes"}
    pro_police_open = {name = "Police Pro Open", min = 0, max = 999}
    ama_police_33_39 = {name = "Police Amateur Submasters 33-39", min = 33, max = 39, tested="Yes"}
    pro_police_33_39 = {name = "Police Pro Submasters 33-39", min = 33, max = 39}
    ama_police_40_44 = {name = "Police Amateur Masters 40-44", min = 40, max = 44, tested="Yes"}
    pro_police_40_44 = {name = "Police Pro Masters 40-44", min = 40, max = 44}
    ama_police_45_49 = {name = "Police Amateur Masters 45-49", min = 45, max = 49, tested="Yes"}
    ama_police_50_54 = {name = "Police Amateur Masters 50-54", min = 50, max = 54, tested="Yes"}
    pro_police_45_49 = {name = "Police Pro Masters 45-49", min = 45, max = 49}
    pro_police_50_54 = {name = "Police Pro Masters 50-54", min = 50, max = 54}
    ama_police_50p = {name = "Police Amateur Masters 50+", min = 50, max = 999, tested="Yes"}
    pro_police_50p = {name = "Police Pro Masters 50+", min = 50, max = 999}
    ama_military_teen_18_19 = {name = "Military Amateur Teen 18-19", min = 18, max = 19, tested="Yes"}
    ama_military_jun = {name = "Military Amateur Juniors 20-23", min = 20, max = 23, tested="Yes"}
    pro_military_jun = {name = "Military Pro Juniors 20-23", min = 20, max = 23}
    ama_military_open = {name = "Military Amateur Open", min = 0, max = 999, tested="Yes"}
    pro_military_open = {name = "Military Pro Open", min = 0, max = 999}
    ama_military_33_39 = {name = "Military Amateur Submasters 33-39", min = 33, max = 39, tested="Yes"}
    ama_military_40_44 = {name = "Military Amateur Masters 40-44", min = 40, max = 44, tested="Yes"}
    ama_military_45_49 = {name = "Military Amateur Masters 45-49", min = 45, max = 49, tested="Yes"}
    ama_military_50p = {name = "Military Amateur Masters 50+", min = 50, max = 999, tested="Yes"}
    ama_military_50_54 = {name = "Military Amateur Masters 50-54", min = 50, max = 54, tested="Yes"}
    ama_military_55_59 = {name = "Military Amateur Masters 55-59", min = 55, max = 59, tested="Yes"}
    ama_military_65_69 = {name = "Military Amateur Masters 65-69", min = 65, max = 69, tested="Yes"}
    pro_military_50p = {name = "Military Pro Masters 50+", min = 50, max = 999}
    pro_military_60_64 = {name = "Military Pro Masters 60-64", min = 60, max = 64}

    # Occupation-based divisions, that have been used although they're not real divisions
    pro_pfm_open = {name = "Police/Fire/Military Pro Open", min = 0, max = 999}
    ama_pfm_open = {name = "Police/Fire/Military Amateur Open", min = 0, max = 999, tested="Yes"}
    pro_pfm_masters_50_54 = {name = "Police/Fire/Military Pro Masters 50-54", min=50, max=54}

    # Adaptive divisions. Not sure what these are.
    adaptive_open= {name = "Adaptive Open", min = 0, max = 999}
    adaptive_juniors = {name = "Adaptive Juniors 20-23", min=20, max=23}
    adaptive_submasters = {name = "Adaptive Submasters 33-39", min=33, max=39}

    # Miscellaneous divisions.
    crossfit = {name = "Crossfit", min = 0, max = 999}
    crossfit_submasters_33_39 = {name="Crossfit Submasters 33-39", min=33, max=39}
    crossfit_masters_45_49 = {name="Crossfit Masters 45-49", min=45, max=49}
    crossfit_masters_60_64 = {name="Crossfit Masters 60-64", min=60, max=64}
    specialolympics = {name = "Special Olympics", min = 0, max = 999}
    paralympic = {name = "Paralympic", min = 0, max = 999}
    adaptive = {name = "Adaptive", min = 0, max = 999}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","110","110+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "F"

[weightclasses.default_Mx]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "Mx"

[exemptions]
    1304 = ["ExemptWeightClassConsistency"]
    1515 = ["ExemptWeightClassConsistency"]
    1636 = ["ExemptWeightClassConsistency"]
    1927 = ["ExemptDivision"] # Not really an RPS meet (GPC-USA).
    1558 = ["ExemptWeightClassConsistency"] #Ernie Lilliebridge's bw was listed as 400lbs as a hilarious joke
    1973 = ["ExemptDivision"] # New divs using OpenLifter; not sure whether to keep.
