[divisions]
    open = {name ="Open",min=14,max=999}
    t1415 = {name ="Teen 14-15",min=14,max=15}
    t1617 = {name ="Teen 16-17",min=16,max=17}
    t1819 = {name ="Teen 18-19",min=18,max=19}
    j2023 = {name ="Juniors 20-23",min=20,max=23}

    m4044 = {name ="Masters 40-44",min=40,max=44}
    m4549 = {name ="Masters 45-49",min=45,max=49}
    m5054 = {name ="Masters 50-54",min=50,max=54}
    m5559 = {name ="Masters 55-59",min=55,max=59}
    m6064 = {name ="Masters 60-64",min=60,max=64}
    m6569 = {name ="Masters 65-69",min=65,max=69}
    m7074 = {name ="Masters 70-74",min=70,max=74}
    m7579 = {name ="Masters 75-79",min=75,max=79}
    m8084 = {name ="Masters 80-84",min=80,max=84}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","145","145+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "M"


[weightclasses.default_F]
    classes = ["44","47.6","50.5","53","55.5","58.5","63","70","80","90","90+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]
