[divisions]
    mor = {name ="MO", min=0, max=999, sex="M", equipment=["Raw","Wraps"]}
    for = {name ="FO", min=0, max=999, sex="F", equipment=["Raw","Wraps"]}
    mtr = {name ="MT", min=13, max=19, sex="M", equipment=["Raw","Wraps"]}
    mt1r = {name ="MT1", min=13, max=15, sex="M", equipment=["Raw","Wraps"]}
    mt2r = {name ="MT2", min=16, max=17, sex="M", equipment=["Raw","Wraps"]}
    mt3r = {name ="MT3", min=18, max=19, sex="M", equipment=["Raw","Wraps"]}
    ftr = {name ="FT", min=13, max=19, sex="F", equipment=["Raw","Wraps"]}
    ft1r = {name ="FT1", min=13, max=15, sex="F", equipment=["Raw","Wraps"]}
    ft2r = {name ="FT2", min=16, max=17, sex="F", equipment=["Raw","Wraps"]}
    ft3r = {name ="FT3", min=18, max=19, sex="F", equipment=["Raw","Wraps"]}
    mjr = {name ="MJ", min=20, max=23, sex="M", equipment=["Raw","Wraps"]}
    fjr = {name ="FJ", min=20, max=23, sex="F", equipment=["Raw","Wraps"]}
    mm1r = {name ="MM1", min=40, max=49, sex="M", equipment=["Raw","Wraps"]}
    fm1r = {name ="FM1", min=40, max=49, sex="F", equipment=["Raw","Wraps"]}
    mm2r = {name ="MM2", min=50, max=59, sex="M", equipment=["Raw","Wraps"]}
    fm2r = {name ="FM2", min=50, max=59, sex="F", equipment=["Raw","Wraps"]}
    mm3r = {name ="MM3", min=60, max=69, sex="M", equipment=["Raw","Wraps"]}
    fm3r = {name ="FM3", min=60, max=69, sex="F", equipment=["Raw","Wraps"]}
    mm4r = {name ="MM4", min=70, max=79, sex="M", equipment=["Raw","Wraps"]}
    fm4r = {name ="FM4", min=70, max=79, sex="F", equipment=["Raw","Wraps"]}
    mm5r = {name ="MM5", min=80, max=89, sex="M", equipment=["Raw","Wraps"]}

    moe = {name ="MOE", min=0, max=999, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mje = {name ="MJE", min=20, max=23, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    met = {name ="MET", min=13, max=19, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    met1 = {name ="MET1", min=13, max=15, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    met2 = {name ="MET2", min=16, max=17, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    met3 = {name ="MET3", min=18, max=19, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mem1 = {name ="MEM1", min=40, max=49, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mem2 = {name ="MEM2", min=50, max=59, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mem3 = {name ="MEM3", min=60, max=69, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mem4 = {name ="MEM4", min=70, max=79, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
    mem5 = {name ="MEM5", min=80, max=89, sex="M", equipment=["Single-ply","Multi-ply","Unlimited"]}
 
    foe = {name ="FOE", min=0, max=999, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}
    fje = {name ="FJE", min=20, max=23, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}
    fet1 = {name ="FET1", min=13, max=15, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}
    fet2 = {name ="FET2", min=16, max=17, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}
    fet3 = {name ="FET3", min=18, max=19, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}
    fem1 = {name ="FEM1", min=40, max=49, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}
    fem2 = {name ="FEM2", min=50, max=59, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}
    fem3 = {name ="FEM3", min=60, max=69, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}
    fem4 = {name ="FEM4", min=70, max=79, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}
    fem5 = {name ="FEM5", min=80, max=89, sex="F", equipment=["Single-ply","Multi-ply","Unlimited"]}

    # Disabled bench
    momozg = {name ="MO-MOZG", min=0, max=999, sex="M", equipment="Raw"}
    mm1mozg = {name ="MM1-MOZG", min=40, max=49, sex="M", equipment="Raw"}
    mt2mozg = {name ="MT2-MOZG", min=16, max=17, sex="M", equipment="Raw"}    
    mjmozg = {name ="MJ-MOZG", min=20, max=23, sex="M", equipment="Raw"}    

    # Elite
    melite = {name ="MElite", min=0, max=999, sex="M", equipment=["Raw","Wraps"]}
    felite = {name ="FElite", min=0, max=999, sex="F", equipment=["Raw","Wraps"]}
[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","125+","140+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]
   1303 = ["ExemptWeightClassConsistency"] # No Weightclasses for Multi-ply
   1401 = ["ExemptWeightClassConsistency"] # Non standard weight classes
   1501 = ["ExemptWeightClassConsistency"] # Non standard weight classes
   1601 = ["ExemptWeightClassConsistency"] # Non standard weight classes