[options]
    require_manual_disambiguation = true

[divisions]
    open = {name="Open", min=0, max=999}

    t1416 = {name="T14-16", min=14, max=16}
    s1719 = {name="S17-19", min=17, max=19}
    j2024 = {name="J20-24", min=20, max=24}
    s2439 = {name="S24-39", min=24, max=39}
    m40p = {name="M40+", min=40, max=999}
    m4049 = {name="M40-49", min=40, max=49}
    m5059 = {name="M50-59", min=50, max=59}
    m6069 = {name="M60-69", min=60, max=69}
    m70p = {name="M70+", min=70, max=999}

    j2023 = {name="J20-23", min=20, max=23}


[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["2022-01-01", "9999-01-01"]
    sex = "F"

# Be careful with exemptions! The "Absoluto" lines should be deleted. Those are points-based.
[exemptions]
