# Configuration for the WPO, intentionally left blank for now

[divisions]

[weightclasses]


[exemptions]
    2402 = ["ExemptDivision"] # Tested lifters
    2503 = ["ExemptDivision"] # Tested lifters