[divisions]
    open = {name ="Open",min=0,max=999}
    jun = {name ="Jun",min=20,max=23}
    m4049 = {name ="M 40-49",min=40,max=49} 
    m5059 = {name ="M 50-59",min=50,max=59} 
    m6069 = {name ="M 60-69",min=60,max=69} 
    m7079 = {name ="M 70-79",min=70,max=79}
    mplus80 = {name ="M 80+",min=80,max=999}  
    m4044 = {name ="M 40-44",min=40,max=44} 
    m4549 = {name ="M 45-49",min=45,max=49}
    m5054 = {name ="M 50-54",min=50,max=54}
    m5559 = {name ="M 55-59",min=55,max=59}  
    m6064 = {name ="M 60-64",min=60,max=64}
    m6569 = {name ="M 65-69",min=65,max=69}   
    m7074 = {name ="M 70-74",min=70,max=74} 
    m7579 = {name ="M 75-79",min=75,max=79}         
    tn1315 = {name ="Tn 13-15",min=13,max=15} 
    tn1617 = {name ="Tn 16-17",min=16,max=17} 
    tn1819 = {name ="Tn 18-19",min=18,max=19} 
    subm = {name ="SubM",min=33,max=39} 
    paraol = {name ="ParaOl",min=0,max=999} 

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","145","140+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]
