# Divisions are specified here: https://www.ipapower.com/pdf/2017/IPA%20GENERAL%20RULES%2011_2017.pdf
[divisions]
    # Note that the Open division is disallowed for lifters under age 20,
    # but meet directors don't seem to have consistently known that.
    # Setting that bound passes checks but breaks age inference all over the place.

    # Amateur divisions.
    ama_teen_13 = {name="Amateur Teen 13", min=0, max=13, tested="Yes"}
    ama_teen_14_15 = {name="Amateur Teen 14-15", min=14, max=15, tested="Yes"}
    ama_teen_16_17 = {name="Amateur Teen 16-17", min=16, max=17, tested="Yes"}
    ama_teen_18_19 = {name="Amateur Teen 18-19", min=18, max=19, tested="Yes"}
    ama_juniors = {name="Amateur Juniors 20-23", min=20, max=23, tested="Yes"}
    ama_open = {name="Amateur Open", min=0, max=999, tested="Yes"}
    ama_submasters = {name="Amateur Submasters 33-39", min=33, max=39, tested="Yes"}
    ama_masters_40_44 = {name="Amateur Masters 40-44", min=40, max=44, tested="Yes"}
    ama_masters_45_49 = {name="Amateur Masters 45-49", min=45, max=49, tested="Yes"}
    ama_masters_50_54 = {name="Amateur Masters 50-54", min=50, max=54, tested="Yes"}
    ama_masters_55_59 = {name="Amateur Masters 55-59", min=55, max=59, tested="Yes"}
    ama_masters_60_64 = {name="Amateur Masters 60-64", min=60, max=64, tested="Yes"}
    ama_masters_65_69 = {name="Amateur Masters 65-69", min=65, max=69, tested="Yes"}
    ama_masters_70_74 = {name="Amateur Masters 70-74", min=70, max=74, tested="Yes"}
    ama_masters_75_79 = {name="Amateur Masters 75-79", min=75, max=79, tested="Yes"}
    ama_masters_80p = {name="Amateur Masters 80+", min=80, max=999, tested="Yes"}
    ama_police = {name="Amateur Police", min=0, max=999, tested="Yes"}

    # Pro divisions.
    pro_teen_13 = {name="Pro Teen 13", min=0, max=13}
    pro_teen_14_15 = {name="Pro Teen 14-15", min=14, max=15}
    pro_teen_16_17 = {name="Pro Teen 16-17", min=16, max=17}
    pro_teen_18_19 = {name="Pro Teen 18-19", min=18, max=19}
    pro_juniors = {name="Pro Juniors 20-23", min=20, max=23}
    pro_open = {name="Pro Open", min=0, max=999}
    pro_submasters = {name="Pro Submasters 33-39", min=33, max=39}
    pro_masters_40_44 = {name="Pro Masters 40-44", min=40, max=44}
    pro_masters_45_49 = {name="Pro Masters 45-49", min=45, max=49}
    pro_masters_50_54 = {name="Pro Masters 50-54", min=50, max=54}
    pro_masters_55_59 = {name="Pro Masters 55-59", min=55, max=59}
    pro_masters_60_64 = {name="Pro Masters 60-64", min=60, max=64}
    pro_masters_65_69 = {name="Pro Masters 65-69", min=65, max=69}
    pro_masters_70_74 = {name="Pro Masters 70-74", min=70, max=74}
    pro_masters_75_79 = {name="Pro Masters 75-79", min=75, max=79}
    pro_masters_80p = {name="Pro Masters 80+", min=80, max=999}


    # Non-standard divisions that make sense to include.
    ama_teen_14_16 = {name="Amateur Teen 14-16", min=14, max=16, tested="Yes"}
    pro_teen_14_16 = {name="Pro Teen 14-16", min=14, max=16}
    ama_teen_17_19 = {name="Amateur Teen 17-19", min=17, max=19, tested="Yes"}
    pro_teen_17_19 = {name="Pro Teen 17-19", min=17, max=19}
    pro_teen = {name="Pro Teen", min=13, max=19}
    pro_masters = {name="Pro Masters", min=40, max=999}

    # Some Russian meets disregarded the rulebook and just used standard divisions.
    # These contain age information, so we might as well interpret them.
    ama_masters_40_49 = {name="Amateur Masters 40-49", min=40, max=49, tested="Yes"}
    ama_masters_50_59 = {name="Amateur Masters 50-59", min=50, max=59, tested="Yes"}
    ama_masters_60_69 = {name="Amateur Masters 60-69", min=60, max=69, tested="Yes"}
    ama_masters_70_79 = {name="Amateur Masters 70-79", min=70, max=79, tested="Yes"}
    pro_masters_40_49 = {name="Pro Masters 40-49", min=40, max=49}
    pro_masters_50_59 = {name="Pro Masters 50-59", min=50, max=59}
    pro_masters_60_69 = {name="Pro Masters 60-69", min=60, max=69}
    pro_masters_70_79 = {name="Pro Masters 70-79", min=70, max=79}

    dis_open = {name="Disabled Open", min=0, max=999}
    dis_teen_13 = {name="Disabled Teen 13", min=0, max=13}
    dis_teen_14_15 = {name="Disabled Teen 14-15", min=14, max=15}
    dis_teen_14_16 = {name="Disabled Teen 14-16", min=14, max=16}
    dis_teen_16_17 = {name="Disabled Teen 16-17", min=16, max=17}
    dis_teen_17_19 = {name="Disabled Teen 17-19", min=17, max=19}
    dis_teen_18_19 = {name="Disabled Teen 18-19", min=18, max=19}
    dis_juniors = {name="Disabled Juniors 20-23", min=20, max=23}
    dis_masters_40_44 = {name="Disabled Masters 40-44", min=40, max=44}
    dis_masters_45_49 = {name="Disabled Masters 45-49", min=45, max=49}
    dis_masters_40_49 = {name="Disabled Masters 40-49", min=40, max=49}
    dis_masters_50_54 = {name="Disabled Masters 50-54", min=50, max=54}
    dis_masters_55_59 = {name="Disabled Masters 55-59", min=55, max=59}
    dis_masters_60_64 = {name="Disabled Masters 60-64", min=60, max=64}
    dis_masters_65_69 = {name="Disabled Masters 65-69", min=65, max=69}


    elite_open = {name="Elite Open", min=0, max=999}
    elite_teen_16_17 = {name="Elite Teen 16-17", min=16, max=17}
    elite_juniors = {name="Elite Juniors 20-23", min=20, max=23}
    elite_masters_40_44 = {name="Elite Masters 40-44", min=40, max=44}
    elite_masters_45_49 = {name="Elite Masters 45-49", min=45, max=49}
    elite_masters_50_54 = {name="Elite Masters 50-54", min=50, max=54}
    elite_masters_55_59 = {name="Elite Masters 55-59", min=55, max=59}
    elite_masters_65_69 = {name="Elite Masters 65-69", min=65, max=69}


[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1900-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["1900-01-01", "9999-01-01"]
    sex = "F"

[weightclasses.youth_M]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1900-01-01", "9999-01-01"]
    sex = "M"
    divisions = ["Amateur Teen 13","Pro Teen 13","Disabled Teen 13"]


[exemptions]
    1303 = ["ExemptWeightClassConsistency"] # Elite lifters with no WC
    1402 = ["ExemptWeightClassConsistency"] # Elite lifters with no WC
    1914 = ["ExemptWeightClassConsistency"] # Non standard WCs
    1944 = ["ExemptWeightClassConsistency"] # Non standard WCs
    1958 = ["ExemptWeightClassConsistency"] # Non standard WCs
    1961 = ["ExemptWeightClassConsistency"] # No WCs
