# Configuration for Powerlifting Australia.

[options]
    require_manual_disambiguation = true


[divisions]
    open = {name ="Open",min=0,max=999}
    novice = {name ="Novice",min=0,max=999}
    under18 = {name = "Under 18",min=0,max=17}
    juniors = {name = "Juniors",min=0,max=22.5}
    subjuniors = {name = "Sub-Juniors",min=0,max=17.5}
    masters1 = {name = "Masters 1",min=39.5,max=48.5}
    masters2 = {name = "Masters 2",min=49.5,max=58.5}
    masters3 = {name = "Masters 3",min=59.5,max=68.5}
    masters4 = {name = "Masters 4",min=69.5,max=999}
    masters5 = {name = "Masters 5",min=79.5,max=999} # ???

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"

[exemptions]
    PA-01-04-02-A = ["ExemptWeightClassConsistency"] # Lifter missing WC
    PA-04-03-05-D = ["ExemptWeightClassConsistency"] # Lifter missing WC
    PA-02-07-06-B = ["ExemptWeightClassConsistency"] # Lifter missing WC
    PA-02-05W-05-D = ["ExemptWeightClassConsistency"] # Lifter missing WC
    PA-01-02-03-A = ["ExemptWeightClassConsistency"] # No weightclasses
    PA-02-05W-04-C = ["ExemptWeightClassConsistency"] # Man in 48kg class
    PA-03-02-04-A = ["ExemptDivision"]
    PA-02-02-07-B = ["ExemptDivision"]
    PA-02-02-07-C = ["ExemptDivision"]
