# Configuration for RhinoPC

[divisions]
    mo = {name ="M-O", min=0, max=999, sex="M", equipment=["Raw","Wraps"]}
    fo = {name ="F-O", min=0, max=999, sex="F", equipment=["Raw","Wraps"]}
    msm = {name ="M-SM", min=33, max=39, sex="M", equipment=["Raw","Wraps"]}
    fsm = {name ="F-SM", min=33, max=39, sex="F", equipment=["Raw","Wraps"]}
    mt1 = {name ="M-T1", min=13, max=15, sex="M", equipment=["Raw","Wraps"]}
    mt2 = {name ="M-T2", min=16, max=17, sex="M", equipment=["Raw","Wraps"]}
    mt3 = {name ="M-T3", min=18, max=19, sex="M", equipment=["Raw","Wraps"]}
    my = {name ="M-Y", min=0, max=12, sex="M", equipment=["Raw","Wraps"]}
    fy = {name ="F-Y", min=0, max=12, sex="F", equipment=["Raw","Wraps"]}
    ft = {name ="F-T", min=13, max=19, sex="F", equipment=["Raw","Wraps"]}
    ft1 = {name ="F-T1", min=13, max=15, sex="F", equipment=["Raw","Wraps"]}
    ft2 = {name ="F-T2", min=16, max=17, sex="F", equipment=["Raw","Wraps"]}
    ft3 = {name ="F-T3", min=18, max=19, sex="F", equipment=["Raw","Wraps"]}
    mj = {name ="M-J", min=20, max=23, sex="M", equipment=["Raw","Wraps"]}
    fj = {name ="F-J", min=20, max=23, sex="F", equipment=["Raw","Wraps"]}
    mm1 = {name ="M-M1", min=40, max=44, sex="M", equipment=["Raw","Wraps"]}
    fm1 = {name ="F-M1", min=40, max=44, sex="F", equipment=["Raw","Wraps"]}
    mm2 = {name ="M-M2", min=45, max=49, sex="M", equipment=["Raw","Wraps"]}
    fm2 = {name ="F-M2", min=45, max=49, sex="F", equipment=["Raw","Wraps"]}
    mm3 = {name ="M-M3", min=50, max=54, sex="M", equipment=["Raw","Wraps"]}
    fm3 = {name ="F-M3", min=50, max=54, sex="F", equipment=["Raw","Wraps"]}
    mm4 = {name ="M-M4", min=55, max=59, sex="M", equipment=["Raw","Wraps"]}
    fm4 = {name ="F-M4", min=55, max=59, sex="F", equipment=["Raw","Wraps"]}
    mm5 = {name ="M-M5", min=60, max=64, sex="M", equipment=["Raw","Wraps"]}
    fm5 = {name ="F-M5", min=60, max=64, sex="F", equipment=["Raw","Wraps"]}
    mm6 = {name ="M-M6", min=65, max=69, sex="M", equipment=["Raw","Wraps"]}
    fm6 = {name ="F-M6", min=65, max=69, sex="F", equipment=["Raw","Wraps"]}
    mm7 = {name ="M-M7", min=70, max=74, sex="M", equipment=["Raw","Wraps"]}
    fm7 = {name ="F-M7", min=70, max=74, sex="F", equipment=["Raw","Wraps"]}
    mm8 = {name ="M-M8", min=75, max=79, sex="M", equipment=["Raw","Wraps"]}
    fm8 = {name ="F-M8", min=75, max=79, sex="F", equipment=["Raw","Wraps"]}
    mm9 = {name ="M-M9", min=80, max=999, sex="M", equipment=["Raw","Wraps"]}
    fm9 = {name ="F-M9", min=80, max=999, sex="F", equipment=["Raw","Wraps"]}
    meo = {name ="M-EO", min=0, max=999, sex="M", equipment=["Single-ply","Multi-ply"]}
    feo = {name ="F-EO", min=0, max=999, sex="F", equipment=["Single-ply","Multi-ply"]}
    mesm = {name ="M-ESM", min=33, max=39, sex="M", equipment=["Single-ply","Multi-ply"]}
    fesm = {name ="F-ESM", min=33, max=39, sex="F", equipment=["Single-ply","Multi-ply"]}
    met1 = {name ="M-ET1", min=13, max=15, sex="M", equipment=["Single-ply","Multi-ply"]}
    met2 = {name ="M-ET2", min=16, max=17, sex="M", equipment=["Single-ply","Multi-ply"]}
    met3 = {name ="M-ET3", min=18, max=19, sex="M", equipment=["Single-ply","Multi-ply"]}
    mey = {name ="M-EY", min=0, max=12, sex="M", equipment=["Single-ply","Multi-ply"]}
    fey = {name ="F-EY", min=0, max=12, sex="F", equipment=["Single-ply","Multi-ply"]}
    fet = {name ="F-ET", min=13, max=19, sex="F", equipment=["Single-ply","Multi-ply"]}
    fet1 = {name ="F-ET1", min=13, max=15, sex="F", equipment=["Single-ply","Multi-ply"]}
    fet2 = {name ="F-ET2", min=16, max=17, sex="F", equipment=["Single-ply","Multi-ply"]}
    fet3 = {name ="F-ET3", min=18, max=19, sex="F", equipment=["Single-ply","Multi-ply"]}
    mej = {name ="M-EJ", min=20, max=23, sex="M", equipment=["Single-ply","Multi-ply"]}
    fej = {name ="F-EJ", min=20, max=23, sex="F", equipment=["Single-ply","Multi-ply"]}
    mem1 = {name ="M-EM1", min=40, max=44, sex="M", equipment=["Single-ply","Multi-ply"]}
    fem1 = {name ="F-EM1", min=40, max=44, sex="F", equipment=["Single-ply","Multi-ply"]}
    mem2 = {name ="M-EM2", min=45, max=49, sex="M", equipment=["Single-ply","Multi-ply"]}
    fem2 = {name ="F-EM2", min=45, max=49, sex="F", equipment=["Single-ply","Multi-ply"]}
    mem3 = {name ="M-EM3", min=50, max=54, sex="M", equipment=["Single-ply","Multi-ply"]}
    fem3 = {name ="F-EM3", min=50, max=54, sex="F", equipment=["Single-ply","Multi-ply"]}
    mem4 = {name ="M-EM4", min=55, max=59, sex="M", equipment=["Single-ply","Multi-ply"]}
    fem4 = {name ="F-EM4", min=55, max=59, sex="F", equipment=["Single-ply","Multi-ply"]}
    mem5 = {name ="M-EM5", min=60, max=64, sex="M", equipment=["Single-ply","Multi-ply"]}
    fem5 = {name ="F-EM5", min=60, max=64, sex="F", equipment=["Single-ply","Multi-ply"]}
    mem6 = {name ="M-EM6", min=65, max=69, sex="M", equipment=["Single-ply","Multi-ply"]}
    fem6 = {name ="F-EM6", min=65, max=69, sex="F", equipment=["Single-ply","Multi-ply"]}
    mem7 = {name ="M-EM7", min=70, max=74, sex="M", equipment=["Single-ply","Multi-ply"]}
    fem7 = {name ="F-EM7", min=70, max=74, sex="F", equipment=["Single-ply","Multi-ply"]}
    mem8 = {name ="M-EM8", min=75, max=79, sex="M", equipment=["Single-ply","Multi-ply"]}
    fem8 = {name ="F-EM8", min=75, max=79, sex="F", equipment=["Single-ply","Multi-ply"]}
    mem9 = {name ="M-EM9", min=80, max=999, sex="M", equipment=["Single-ply","Multi-ply"]}
    fem9 = {name ="F-EM9", min=80, max=999, sex="F", equipment=["Single-ply","Multi-ply"]}


[weightclasses.default_M]
    classes = ["56","60","67.5","75","82.5","90","100","110","125","140","125+","140+"]
    date_range = ["2016-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","110","110+"]
    date_range = ["2022-11-01","9999-01-01"]
    sex = "F"

[weightclasses.oldish_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","110","110+"]
    date_range = ["2016-01-01","2022-10-31"]
    sex = "F"

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2015-12-31"]
    sex = "F"

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","125+","140+"]
    date_range = ["0000-01-01","2015-12-31"]
    sex = "M"

[exemptions]
    2206 = ["ExemptWeightClassConsistency"] # Reduced weight classes.
