# https://www.powerlifting.ch/fileadmin/user_upload/Dokumente/Reglemente/Swiss_Powerlifting/Kategorieneinteilung_DE.pdf
# 
# SwissPL used to be a combination of lots of multiple federations:
#   GPC, WUAP, and some other untested fed.
# Since 2019 they revised to be exclusively IPF.

[divisions]
    # Traditional, pre-IPF divisions.
    open = {name="Open", min=0, max=999}
    t13_15 = {name="T13-15", min=13, max=15}
    t16_17 = {name="T16-17", min=16, max=17}
    t18_19 = {name="T18-19", min=18, max=19}
    juniors = {name="Juniors", min=18, max=23}
    m40_44 = {name="M40-44", min=40, max=44}
    m45_49 = {name="M45-49", min=45, max=49}
    m50_54 = {name="M50-54", min=50, max=54}
    m55_59 = {name="M55-59", min=55, max=59}
    m60_64 = {name="M60-64", min=60, max=64}
    m65_69 = {name="M65-69", min=65, max=69}
    m70_74 = {name="M70-74", min=70, max=74}
    m75_79 = {name="M75-79", min=75, max=79}
    m80p = {name="M80+", min=80, max=999}

    #IPF division
    master1 = {name="Masters I",min=39.5,max=48.5}
    master2 = {name="Masters II",min=49.5,max=58.5}
    master3 = {name="Masters III",min=59.5,max=68.5}
    master4 = {name="Masters IV",min=69.5,max=999}
    subjunior = {name="Sub-Juniors", min=0, max=17.5}

[weightclasses.traditional_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1999-01-01", "2018-12-31"]
    sex = "M"

[weightclasses.traditional_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["1999-01-01", "2018-12-31"]
    sex = "F"

[weightclasses.IPF_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range = ["2019-01-01", "9999-12-31"]
    sex = "M"

[weightclasses.IPF_F]
    classes = ["47","52","57","63","72","84","84+"]
    date_range = ["2019-01-01", "9999-12-31"]
    sex = "F"

[exemptions]
    # Limited weightclasses. Juniors and Sub-Juniors combined.
    0605 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    0606 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses.
    1902 = ["ExemptWeightClassConsistency", "ExemptDivision"]
    1701 = ["ExemptWeightClassConsistency", "ExemptDivision"]
