[divisions]
    open = {name ="Open",min=0,max=999}
    under14 = {name = "Under 14",min=0,max=14}
    under15 = {name = "Under 15",min=0,max=15}
    under17 = {name = "Under 17",min=0,max=17}
    under18 = {name = "Under 18",min=0,max=17.5}
    under20 = {name = "Under 20",min=0,max=19.5}
    under23 = {name = "Under 23",min=0,max=22.5}
    over40 = {name = "Over 40",min=39.5,max=999}
    over50 = {name = "Over 50",min=49.5,max=999}
    over60 = {name = "Over 60",min=59.5,max=999}
    over70 = {name = "Over 70",min=69.5,max=999}
    paralympics = {name = "Paralympics",min=0,max=999}

[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"

[weightclasses.junior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["Under 23","Under 20"]

[weightclasses.teen_M]
    classes = ["53","59","66","74","83","93","105","120","105+","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["Under 18","Under 17","Under 15","Under 14"]

[weightclasses.junior_F]
    classes = ["43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"
    divisions = ["Under 23","Under 20","Under 17","Under 15","Under 14"]

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["1980-01-01","2010-12-31"]
    sex = "M"

[weightclasses.old2_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","110+"]
    date_range = ["0000-01-01","1979-12-31"]
    sex = "M"

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"

[weightclasses.oldteen_M]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"
    divisions = ["Under 18","Under 17","Under 15","Under 14"]

[exemptions]
    15008 = ["check_row_division"]
    16063 = ["check_row_division"]
    16064 = ["check_row_division"]
    16016 = ["check_row_division"]
    83004 = ["check_row_weightclass_consistency"]
    80005 = ["check_row_weightclass_consistency"]
    11002 = ["check_row_weightclass_consistency"]
    16079 = ["check_row_weightclass_consistency"]

