# Configuration for WRPF-Costa Rica.

[options]
    require_manual_disambiguation = true

[divisions]
    #Official WRPF divisions
    open = {name = "Open", min = 0, max = 999}
    youth = {name = "Youth", min = 4, max = 13}
    teen_14_16 = {name = "Teen 14-16", min = 14, max = 16}
    teen_17_19 = {name = "Teen 17-19", min = 17, max = 19}
    juniors_20_23 = {name = "Juniors 20-23", min = 20, max = 23}
    submasters = {name = "Submasters 35-39", min = 35, max = 39}
    m1 = {name = "Masters 40-49", min = 40, max = 49}
    m2 = {name = "Masters 50-59", min = 50, max = 59}
    m3 = {name = "Masters 60-69", min = 60, max = 69}
    m4 = {name = "Masters 70-79", min = 70, max = 79}
    m5 = {name = "Masters 80-89", min = 80, max = 89}


[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "M"


[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["2022-12-01", "9999-01-01"]
    sex = "F"


[exemptions]
